# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'base_path_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_basePathDialog(object):
    def setupUi(self, basePathDialog):
        basePathDialog.setObjectName("basePathDialog")
        basePathDialog.resize(664, 744)
        self.gridLayout_3 = QtWidgets.QGridLayout(basePathDialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(basePathDialog)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(basePathDialog)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 2)
        self.basePath = QtWidgets.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.basePath.setFont(font)
        self.basePath.setObjectName("basePath")
        self.gridLayout_2.addWidget(self.basePath, 1, 0, 1, 1)
        self.browseBase = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.browseBase.setFont(font)
        self.browseBase.setObjectName("browseBase")
        self.gridLayout_2.addWidget(self.browseBase, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.musclePath = QtWidgets.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.musclePath.setFont(font)
        self.musclePath.setObjectName("musclePath")
        self.gridLayout_2.addWidget(self.musclePath, 3, 0, 1, 1)
        self.browseMuscle = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.browseMuscle.setFont(font)
        self.browseMuscle.setObjectName("browseMuscle")
        self.gridLayout_2.addWidget(self.browseMuscle, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 4, 0, 1, 1)
        self.clustaloPath = QtWidgets.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.clustaloPath.setFont(font)
        self.clustaloPath.setObjectName("clustaloPath")
        self.gridLayout_2.addWidget(self.clustaloPath, 5, 0, 1, 1)
        self.browseClustal = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.browseClustal.setFont(font)
        self.browseClustal.setObjectName("browseClustal")
        self.gridLayout_2.addWidget(self.browseClustal, 5, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 6, 0, 1, 1)
        self.pymolPath = QtWidgets.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pymolPath.setFont(font)
        self.pymolPath.setObjectName("pymolPath")
        self.gridLayout_2.addWidget(self.pymolPath, 7, 0, 1, 1)
        self.browsePymol = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.browsePymol.setFont(font)
        self.browsePymol.setObjectName("browsePymol")
        self.gridLayout_2.addWidget(self.browsePymol, 7, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 8, 0, 1, 1)
        self.RaxmlPath = QtWidgets.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.RaxmlPath.setFont(font)
        self.RaxmlPath.setObjectName("RaxmlPath")
        self.gridLayout_2.addWidget(self.RaxmlPath, 9, 0, 1, 1)
        self.browseRaxml = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.browseRaxml.setFont(font)
        self.browseRaxml.setObjectName("browseRaxml")
        self.gridLayout_2.addWidget(self.browseRaxml, 9, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 10, 0, 1, 1)
        self.FigtreePath = QtWidgets.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.FigtreePath.setFont(font)
        self.FigtreePath.setObjectName("FigtreePath")
        self.gridLayout_2.addWidget(self.FigtreePath, 11, 0, 1, 1)
        self.browseFigtree = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.browseFigtree.setFont(font)
        self.browseFigtree.setObjectName("browseFigtree")
        self.gridLayout_2.addWidget(self.browseFigtree, 11, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 1, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(basePathDialog)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.FragmentDB_path = QtWidgets.QLineEdit(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.FragmentDB_path.setFont(font)
        self.FragmentDB_path.setObjectName("FragmentDB_path")
        self.gridLayout_4.addWidget(self.FragmentDB_path, 0, 0, 1, 1)
        self.browseFragmentDB = QtWidgets.QPushButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.browseFragmentDB.setFont(font)
        self.browseFragmentDB.setObjectName("browseFragmentDB")
        self.gridLayout_4.addWidget(self.browseFragmentDB, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_3, 2, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(basePathDialog)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.IPinput = QtWidgets.QLineEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.IPinput.setFont(font)
        self.IPinput.setObjectName("IPinput")
        self.gridLayout.addWidget(self.IPinput, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 2, 1, 1)
        self.Portinput = QtWidgets.QLineEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Portinput.setFont(font)
        self.Portinput.setObjectName("Portinput")
        self.gridLayout.addWidget(self.Portinput, 0, 3, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 5, 1, 1)
        self.DBnameinput = QtWidgets.QLineEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.DBnameinput.setFont(font)
        self.DBnameinput.setObjectName("DBnameinput")
        self.gridLayout.addWidget(self.DBnameinput, 0, 6, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.Userinput = QtWidgets.QLineEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Userinput.setFont(font)
        self.Userinput.setObjectName("Userinput")
        self.gridLayout.addWidget(self.Userinput, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 2, 1, 2)
        self.Passinput = QtWidgets.QLineEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Passinput.setFont(font)
        self.Passinput.setObjectName("Passinput")
        self.gridLayout.addWidget(self.Passinput, 1, 4, 1, 3)
        self.gridLayout_3.addWidget(self.groupBox_2, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.yes = QtWidgets.QPushButton(basePathDialog)
        self.yes.setDefault(True)
        self.yes.setObjectName("yes")
        self.horizontalLayout.addWidget(self.yes)
        self.no = QtWidgets.QPushButton(basePathDialog)
        self.no.setObjectName("no")
        self.horizontalLayout.addWidget(self.no)
        self.gridLayout_3.addLayout(self.horizontalLayout, 4, 0, 1, 1)

        self.retranslateUi(basePathDialog)
        QtCore.QMetaObject.connectSlotsByName(basePathDialog)

    def retranslateUi(self, basePathDialog):
        _translate = QtCore.QCoreApplication.translate
        basePathDialog.setWindowTitle(_translate("basePathDialog", "Path Setting"))
        self.label_2.setText(_translate("basePathDialog", "You can set your path by typing or click button to browse:"))
        self.groupBox.setTitle(_translate("basePathDialog", "Path Setting"))
        self.label.setText(_translate("basePathDialog", "Your current base path is: (Only change this when you know what you\'re doning)"))
        self.browseBase.setText(_translate("basePathDialog", "Browse"))
        self.label_3.setText(_translate("basePathDialog", "Your current muscle path is:"))
        self.browseMuscle.setText(_translate("basePathDialog", "Browse"))
        self.label_4.setText(_translate("basePathDialog", "Your current Clustal Omega path is:"))
        self.browseClustal.setText(_translate("basePathDialog", "Browse"))
        self.label_5.setText(_translate("basePathDialog", "Your current PyMOL path is:"))
        self.browsePymol.setText(_translate("basePathDialog", "Browse"))
        self.label_6.setText(_translate("basePathDialog", "Your current RAxML path is:"))
        self.browseRaxml.setText(_translate("basePathDialog", "Browse"))
        self.label_12.setText(_translate("basePathDialog", "Your current FigTree path is:"))
        self.browseFigtree.setText(_translate("basePathDialog", "Browse"))
        self.groupBox_3.setTitle(_translate("basePathDialog", "Local Fragment Database Setting"))
        self.browseFragmentDB.setText(_translate("basePathDialog", "Browse"))
        self.groupBox_2.setTitle(_translate("basePathDialog", "Remote Database Setting"))
        self.label_7.setText(_translate("basePathDialog", "Server IP"))
        self.label_11.setText(_translate("basePathDialog", "Port"))
        self.label_9.setText(_translate("basePathDialog", "DB name"))
        self.label_8.setText(_translate("basePathDialog", "User Name"))
        self.label_10.setText(_translate("basePathDialog", "Password"))
        self.yes.setText(_translate("basePathDialog", "Confirm"))
        self.no.setText(_translate("basePathDialog", "Cancel"))
