# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'base_path_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_basePathDialog(object):
    def setupUi(self, basePathDialog):
        basePathDialog.setObjectName("basePathDialog")
        basePathDialog.resize(739, 396)
        self.label = QtWidgets.QLabel(basePathDialog)
        self.label.setGeometry(QtCore.QRect(40, 60, 441, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(basePathDialog)
        self.label_2.setGeometry(QtCore.QRect(40, 20, 521, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.basePath = QtWidgets.QLineEdit(basePathDialog)
        self.basePath.setGeometry(QtCore.QRect(40, 80, 531, 31))
        self.basePath.setObjectName("basePath")
        self.browseBase = QtWidgets.QPushButton(basePathDialog)
        self.browseBase.setGeometry(QtCore.QRect(590, 80, 113, 32))
        self.browseBase.setObjectName("browseBase")
        self.horizontalLayoutWidget = QtWidgets.QWidget(basePathDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 340, 661, 32))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.yes = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.yes.setDefault(True)
        self.yes.setObjectName("yes")
        self.horizontalLayout.addWidget(self.yes)
        self.no = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.no.setObjectName("no")
        self.horizontalLayout.addWidget(self.no)
        self.musclePath = QtWidgets.QLineEdit(basePathDialog)
        self.musclePath.setGeometry(QtCore.QRect(40, 150, 531, 31))
        self.musclePath.setObjectName("musclePath")
        self.browseMuscle = QtWidgets.QPushButton(basePathDialog)
        self.browseMuscle.setGeometry(QtCore.QRect(590, 150, 113, 32))
        self.browseMuscle.setObjectName("browseMuscle")
        self.clustaloPath = QtWidgets.QLineEdit(basePathDialog)
        self.clustaloPath.setGeometry(QtCore.QRect(40, 220, 531, 31))
        self.clustaloPath.setObjectName("clustaloPath")
        self.browseClustal = QtWidgets.QPushButton(basePathDialog)
        self.browseClustal.setGeometry(QtCore.QRect(590, 220, 113, 32))
        self.browseClustal.setObjectName("browseClustal")
        self.pymolPath = QtWidgets.QLineEdit(basePathDialog)
        self.pymolPath.setGeometry(QtCore.QRect(40, 290, 531, 31))
        self.pymolPath.setObjectName("pymolPath")
        self.browsePymol = QtWidgets.QPushButton(basePathDialog)
        self.browsePymol.setGeometry(QtCore.QRect(590, 290, 113, 32))
        self.browsePymol.setObjectName("browsePymol")
        self.label_3 = QtWidgets.QLabel(basePathDialog)
        self.label_3.setGeometry(QtCore.QRect(40, 130, 441, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(basePathDialog)
        self.label_4.setGeometry(QtCore.QRect(40, 200, 441, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(basePathDialog)
        self.label_5.setGeometry(QtCore.QRect(40, 270, 441, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(basePathDialog)
        QtCore.QMetaObject.connectSlotsByName(basePathDialog)

    def retranslateUi(self, basePathDialog):
        _translate = QtCore.QCoreApplication.translate
        basePathDialog.setWindowTitle(_translate("basePathDialog", "Dialog"))
        self.label.setText(_translate("basePathDialog", "Your current base path is:"))
        self.label_2.setText(_translate("basePathDialog", "You can set your path by typing or click button to browse:"))
        self.browseBase.setText(_translate("basePathDialog", "Browse"))
        self.yes.setText(_translate("basePathDialog", "Confirm"))
        self.no.setText(_translate("basePathDialog", "Cancel"))
        self.browseMuscle.setText(_translate("basePathDialog", "Browse"))
        self.browseClustal.setText(_translate("basePathDialog", "Browse"))
        self.browsePymol.setText(_translate("basePathDialog", "Browse"))
        self.label_3.setText(_translate("basePathDialog", "Your current muscle path is:"))
        self.label_4.setText(_translate("basePathDialog", "Your current Clustal Omega path is:"))
        self.label_5.setText(_translate("basePathDialog", "Your current PyMOL path is:"))


