# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'base_path_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_basePathDialog(object):
    def setupUi(self, basePathDialog):
        basePathDialog.setObjectName("basePathDialog")
        basePathDialog.resize(659, 769)
        self.label_2 = QtWidgets.QLabel(basePathDialog)
        self.label_2.setGeometry(QtCore.QRect(40, 20, 521, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(basePathDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 710, 601, 32))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.yes = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.yes.setDefault(True)
        self.yes.setObjectName("yes")
        self.horizontalLayout.addWidget(self.yes)
        self.no = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.no.setObjectName("no")
        self.horizontalLayout.addWidget(self.no)
        self.groupBox = QtWidgets.QGroupBox(basePathDialog)
        self.groupBox.setGeometry(QtCore.QRect(30, 70, 601, 481))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.browseBase = QtWidgets.QPushButton(self.groupBox)
        self.browseBase.setGeometry(QtCore.QRect(470, 80, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.browseBase.setFont(font)
        self.browseBase.setObjectName("browseBase")
        self.browsePymol = QtWidgets.QPushButton(self.groupBox)
        self.browsePymol.setGeometry(QtCore.QRect(470, 290, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.browsePymol.setFont(font)
        self.browsePymol.setObjectName("browsePymol")
        self.browseMuscle = QtWidgets.QPushButton(self.groupBox)
        self.browseMuscle.setGeometry(QtCore.QRect(470, 150, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.browseMuscle.setFont(font)
        self.browseMuscle.setObjectName("browseMuscle")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 60, 531, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pymolPath = QtWidgets.QLineEdit(self.groupBox)
        self.pymolPath.setGeometry(QtCore.QRect(10, 290, 461, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pymolPath.setFont(font)
        self.pymolPath.setObjectName("pymolPath")
        self.basePath = QtWidgets.QLineEdit(self.groupBox)
        self.basePath.setGeometry(QtCore.QRect(10, 80, 461, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.basePath.setFont(font)
        self.basePath.setObjectName("basePath")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 200, 441, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 270, 441, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.clustaloPath = QtWidgets.QLineEdit(self.groupBox)
        self.clustaloPath.setGeometry(QtCore.QRect(10, 220, 461, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.clustaloPath.setFont(font)
        self.clustaloPath.setObjectName("clustaloPath")
        self.musclePath = QtWidgets.QLineEdit(self.groupBox)
        self.musclePath.setGeometry(QtCore.QRect(10, 150, 461, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.musclePath.setFont(font)
        self.musclePath.setObjectName("musclePath")
        self.browseClustal = QtWidgets.QPushButton(self.groupBox)
        self.browseClustal.setGeometry(QtCore.QRect(470, 220, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.browseClustal.setFont(font)
        self.browseClustal.setObjectName("browseClustal")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 441, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.browseRaxml = QtWidgets.QPushButton(self.groupBox)
        self.browseRaxml.setGeometry(QtCore.QRect(470, 360, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.browseRaxml.setFont(font)
        self.browseRaxml.setObjectName("browseRaxml")
        self.RaxmlPath = QtWidgets.QLineEdit(self.groupBox)
        self.RaxmlPath.setGeometry(QtCore.QRect(10, 360, 461, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.RaxmlPath.setFont(font)
        self.RaxmlPath.setObjectName("RaxmlPath")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 340, 441, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.browseFigtree = QtWidgets.QPushButton(self.groupBox)
        self.browseFigtree.setGeometry(QtCore.QRect(470, 430, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.browseFigtree.setFont(font)
        self.browseFigtree.setObjectName("browseFigtree")
        self.FigtreePath = QtWidgets.QLineEdit(self.groupBox)
        self.FigtreePath.setGeometry(QtCore.QRect(10, 430, 461, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.FigtreePath.setFont(font)
        self.FigtreePath.setObjectName("FigtreePath")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(10, 410, 441, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.groupBox_2 = QtWidgets.QGroupBox(basePathDialog)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 570, 601, 121))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(20, 30, 79, 59))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(20, 80, 79, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(310, 80, 79, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(310, 40, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.Passinput = QtWidgets.QLineEdit(self.groupBox_2)
        self.Passinput.setGeometry(QtCore.QRect(380, 80, 199, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Passinput.setFont(font)
        self.Passinput.setObjectName("Passinput")
        self.DBnameinput = QtWidgets.QLineEdit(self.groupBox_2)
        self.DBnameinput.setGeometry(QtCore.QRect(478, 50, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.DBnameinput.setFont(font)
        self.DBnameinput.setObjectName("DBnameinput")
        self.Portinput = QtWidgets.QLineEdit(self.groupBox_2)
        self.Portinput.setGeometry(QtCore.QRect(350, 50, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Portinput.setFont(font)
        self.Portinput.setObjectName("Portinput")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(410, 40, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.IPinput = QtWidgets.QLineEdit(self.groupBox_2)
        self.IPinput.setGeometry(QtCore.QRect(100, 50, 199, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.IPinput.setFont(font)
        self.IPinput.setObjectName("IPinput")
        self.Userinput = QtWidgets.QLineEdit(self.groupBox_2)
        self.Userinput.setGeometry(QtCore.QRect(100, 80, 199, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Userinput.setFont(font)
        self.Userinput.setObjectName("Userinput")

        self.retranslateUi(basePathDialog)
        QtCore.QMetaObject.connectSlotsByName(basePathDialog)

    def retranslateUi(self, basePathDialog):
        _translate = QtCore.QCoreApplication.translate
        basePathDialog.setWindowTitle(_translate("basePathDialog", "Path Setting"))
        self.label_2.setText(_translate("basePathDialog", "You can set your path by typing or click button to browse:"))
        self.yes.setText(_translate("basePathDialog", "Confirm"))
        self.no.setText(_translate("basePathDialog", "Cancel"))
        self.groupBox.setTitle(_translate("basePathDialog", "Path Setting"))
        self.browseBase.setText(_translate("basePathDialog", "Browse"))
        self.browsePymol.setText(_translate("basePathDialog", "Browse"))
        self.browseMuscle.setText(_translate("basePathDialog", "Browse"))
        self.label.setText(_translate("basePathDialog", "Your current base path is: (Only change this when you know what you\'re doning)"))
        self.label_4.setText(_translate("basePathDialog", "Your current Clustal Omega path is:"))
        self.label_5.setText(_translate("basePathDialog", "Your current PyMOL path is:"))
        self.browseClustal.setText(_translate("basePathDialog", "Browse"))
        self.label_3.setText(_translate("basePathDialog", "Your current muscle path is:"))
        self.browseRaxml.setText(_translate("basePathDialog", "Browse"))
        self.label_6.setText(_translate("basePathDialog", "Your current RAxML path is:"))
        self.browseFigtree.setText(_translate("basePathDialog", "Browse"))
        self.label_12.setText(_translate("basePathDialog", "Your current FigTree path is:"))
        self.groupBox_2.setTitle(_translate("basePathDialog", "Remote Database Setting"))
        self.label_7.setText(_translate("basePathDialog", "Server IP"))
        self.label_8.setText(_translate("basePathDialog", "User Name"))
        self.label_10.setText(_translate("basePathDialog", "Password"))
        self.label_11.setText(_translate("basePathDialog", "Port"))
        self.label_9.setText(_translate("basePathDialog", "DB name"))


