# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fusiondialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_fusionDialog(object):
    def setupUi(self, fusionDialog):
        fusionDialog.setObjectName("fusionDialog")
        fusionDialog.resize(1643, 1068)
        self.gridLayout = QtWidgets.QGridLayout(fusionDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.confirmButton = QtWidgets.QPushButton(fusionDialog)
        self.confirmButton.setDefault(True)
        self.confirmButton.setObjectName("confirmButton")
        self.horizontalLayout.addWidget(self.confirmButton)
        self.cancelButton = QtWidgets.QPushButton(fusionDialog)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(fusionDialog)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 300))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 400))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout.addWidget(self.groupBox, 2, 0, 1, 2)
        self.groupBox_2 = QtWidgets.QGroupBox(fusionDialog)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 400))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_base = QtWidgets.QLabel(self.groupBox_2)
        self.label_base.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_base.setObjectName("label_base")
        self.gridLayout_2.addWidget(self.label_base, 0, 1, 1, 1)
        self.label_donor = QtWidgets.QLabel(self.groupBox_2)
        self.label_donor.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_donor.setObjectName("label_donor")
        self.gridLayout_2.addWidget(self.label_donor, 0, 2, 1, 1)
        self.selection = QtWidgets.QListWidget(self.groupBox_2)
        self.selection.setMinimumSize(QtCore.QSize(0, 0))
        self.selection.setMaximumSize(QtCore.QSize(250, 16777215))
        self.selection.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.selection.setObjectName("selection")
        self.gridLayout_2.addWidget(self.selection, 1, 0, 1, 1)
        self.textEditBase = QtWidgets.QTextEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        self.textEditBase.setFont(font)
        self.textEditBase.setObjectName("textEditBase")
        self.gridLayout_2.addWidget(self.textEditBase, 1, 1, 1, 1)
        self.textEditDonor = QtWidgets.QTextEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        self.textEditDonor.setFont(font)
        self.textEditDonor.setObjectName("textEditDonor")
        self.gridLayout_2.addWidget(self.textEditDonor, 1, 2, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.basename = QtWidgets.QLineEdit(self.groupBox_2)
        self.basename.setReadOnly(True)
        self.basename.setObjectName("basename")
        self.verticalLayout_3.addWidget(self.basename)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.startBase = QtWidgets.QSpinBox(self.groupBox_2)
        self.startBase.setMaximum(5000)
        self.startBase.setObjectName("startBase")
        self.horizontalLayout_2.addWidget(self.startBase)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.endBase = QtWidgets.QSpinBox(self.groupBox_2)
        self.endBase.setMaximum(5000)
        self.endBase.setObjectName("endBase")
        self.horizontalLayout_2.addWidget(self.endBase)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.startDonor = QtWidgets.QSpinBox(self.groupBox_2)
        self.startDonor.setEnabled(False)
        self.startDonor.setMaximum(5000)
        self.startDonor.setObjectName("startDonor")
        self.horizontalLayout_3.addWidget(self.startDonor)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.endDonor = QtWidgets.QSpinBox(self.groupBox_2)
        self.endDonor.setEnabled(False)
        self.endDonor.setMaximum(5000)
        self.endDonor.setObjectName("endDonor")
        self.horizontalLayout_3.addWidget(self.endDonor)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.apply = QtWidgets.QPushButton(self.groupBox_2)
        self.apply.setMinimumSize(QtCore.QSize(100, 60))
        self.apply.setObjectName("apply")
        self.horizontalLayout_4.addWidget(self.apply)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 2, 0, 1, 3)
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 2)

        self.retranslateUi(fusionDialog)
        QtCore.QMetaObject.connectSlotsByName(fusionDialog)

    def retranslateUi(self, fusionDialog):
        _translate = QtCore.QCoreApplication.translate
        fusionDialog.setWindowTitle(_translate("fusionDialog", "Sequence Fusion across subtypes"))
        self.confirmButton.setText(_translate("fusionDialog", "Confirm"))
        self.cancelButton.setText(_translate("fusionDialog", "Cancel"))
        self.groupBox.setTitle(_translate("fusionDialog", "Current product"))
        self.groupBox_2.setTitle(_translate("fusionDialog", "Design"))
        self.label.setText(_translate("fusionDialog", "Select donor sequence:"))
        self.label_base.setText(_translate("fusionDialog", "Base Sequence: "))
        self.label_donor.setText(_translate("fusionDialog", "Donor Sequence: "))
        self.label_2.setText(_translate("fusionDialog", "Current Base sequence:"))
        self.label_3.setText(_translate("fusionDialog", "Replaced region on base sequence:"))
        self.label_5.setText(_translate("fusionDialog", "to"))
        self.label_4.setText(_translate("fusionDialog", "Donor region on donor sequence:"))
        self.label_6.setText(_translate("fusionDialog", "to"))
        self.apply.setText(_translate("fusionDialog", "Add"))
