# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fusiondialog.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_fusionDialog(object):
    def setupUi(self, fusionDialog):
        fusionDialog.setObjectName("fusionDialog")
        fusionDialog.resize(716, 868)
        self.gridLayout = QtWidgets.QGridLayout(fusionDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(fusionDialog)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 4)
        self.label = QtWidgets.QLabel(fusionDialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 3)
        self.selection = QtWidgets.QListWidget(fusionDialog)
        self.selection.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.selection.setObjectName("selection")
        self.gridLayout.addWidget(self.selection, 2, 0, 1, 4)
        self.label_2 = QtWidgets.QLabel(fusionDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 3)
        self.basename = QtWidgets.QLineEdit(fusionDialog)
        self.basename.setReadOnly(True)
        self.basename.setObjectName("basename")
        self.gridLayout.addWidget(self.basename, 4, 0, 1, 4)
        self.label_3 = QtWidgets.QLabel(fusionDialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 3)
        self.groupBox = QtWidgets.QGroupBox(fusionDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.showButton = QtWidgets.QPushButton(self.groupBox)
        self.showButton.setGeometry(QtCore.QRect(0, 40, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.showButton.setFont(font)
        self.showButton.setObjectName("showButton")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 80, 221, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.dna = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.dna.setFont(font)
        self.dna.setChecked(False)
        self.dna.setAutoExclusive(False)
        self.dna.setObjectName("dna")
        self.horizontalLayout_2.addWidget(self.dna)
        self.aa = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.aa.setFont(font)
        self.aa.setChecked(True)
        self.aa.setAutoExclusive(False)
        self.aa.setObjectName("aa")
        self.horizontalLayout_2.addWidget(self.aa)
        self.ba = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.ba.setFont(font)
        self.ba.setChecked(True)
        self.ba.setAutoExclusive(False)
        self.ba.setObjectName("ba")
        self.horizontalLayout_2.addWidget(self.ba)
        self.gridLayout.addWidget(self.groupBox, 5, 3, 4, 1)
        self.startBase = QtWidgets.QLineEdit(fusionDialog)
        self.startBase.setObjectName("startBase")
        self.gridLayout.addWidget(self.startBase, 6, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(fusionDialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 1, 1, 1)
        self.endBase = QtWidgets.QLineEdit(fusionDialog)
        self.endBase.setObjectName("endBase")
        self.gridLayout.addWidget(self.endBase, 6, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(fusionDialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 7, 0, 1, 3)
        self.startDonor = QtWidgets.QLineEdit(fusionDialog)
        self.startDonor.setObjectName("startDonor")
        self.gridLayout.addWidget(self.startDonor, 8, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(fusionDialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 8, 1, 1, 1)
        self.endDonor = QtWidgets.QLineEdit(fusionDialog)
        self.endDonor.setObjectName("endDonor")
        self.gridLayout.addWidget(self.endDonor, 8, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.confirmButton = QtWidgets.QPushButton(fusionDialog)
        self.confirmButton.setDefault(True)
        self.confirmButton.setObjectName("confirmButton")
        self.horizontalLayout.addWidget(self.confirmButton)
        self.cancelButton = QtWidgets.QPushButton(fusionDialog)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.gridLayout.addLayout(self.horizontalLayout, 9, 0, 1, 4)

        self.retranslateUi(fusionDialog)
        QtCore.QMetaObject.connectSlotsByName(fusionDialog)

    def retranslateUi(self, fusionDialog):
        _translate = QtCore.QCoreApplication.translate
        fusionDialog.setWindowTitle(_translate("fusionDialog", "Sequence Fusion across subtypes"))
        self.label_7.setText(_translate("fusionDialog", "Design your HA sequence across subtypes using SequenceFusion function"))
        self.label.setText(_translate("fusionDialog", "Select donor sequence from the following list:"))
        self.label_2.setText(_translate("fusionDialog", "Current Base sequence:"))
        self.label_3.setText(_translate("fusionDialog", "Replaced region on base sequence:"))
        self.groupBox.setTitle(_translate("fusionDialog", "Show Alignment for Base and Donor"))
        self.showButton.setText(_translate("fusionDialog", "Show Alignment"))
        self.dna.setText(_translate("fusionDialog", "DNA"))
        self.aa.setText(_translate("fusionDialog", "AA"))
        self.ba.setText(_translate("fusionDialog", "BA"))
        self.label_5.setText(_translate("fusionDialog", "to"))
        self.label_4.setText(_translate("fusionDialog", "Donor region on donor sequence:"))
        self.label_6.setText(_translate("fusionDialog", "to"))
        self.confirmButton.setText(_translate("fusionDialog", "Confirm"))
        self.cancelButton.setText(_translate("fusionDialog", "Cancel"))


