# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gibsonalignmentdialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GibsonMSADialog(object):
    def setupUi(self, GibsonMSADialog):
        GibsonMSADialog.setObjectName("GibsonMSADialog")
        GibsonMSADialog.resize(1353, 683)
        self.gridLayout = QtWidgets.QGridLayout(GibsonMSADialog)
        self.gridLayout.setObjectName("gridLayout")
        self.nameList = QtWidgets.QListWidget(GibsonMSADialog)
        self.nameList.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        self.nameList.setFont(font)
        self.nameList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.nameList.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.nameList.setObjectName("nameList")
        self.gridLayout.addWidget(self.nameList, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(GibsonMSADialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.seqEditF1 = QtWidgets.QTextEdit(self.tab)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(15)
        self.seqEditF1.setFont(font)
        self.seqEditF1.setLineWidth(1)
        self.seqEditF1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.seqEditF1.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.seqEditF1.setLineWrapColumnOrWidth(0)
        self.seqEditF1.setObjectName("seqEditF1")
        self.gridLayout_2.addWidget(self.seqEditF1, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.seqEditF2 = QtWidgets.QTextEdit(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(15)
        self.seqEditF2.setFont(font)
        self.seqEditF2.setLineWidth(1)
        self.seqEditF2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.seqEditF2.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.seqEditF2.setLineWrapColumnOrWidth(0)
        self.seqEditF2.setObjectName("seqEditF2")
        self.gridLayout_3.addWidget(self.seqEditF2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.seqEditF3 = QtWidgets.QTextEdit(self.tab_3)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(15)
        self.seqEditF3.setFont(font)
        self.seqEditF3.setLineWidth(1)
        self.seqEditF3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.seqEditF3.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.seqEditF3.setLineWrapColumnOrWidth(0)
        self.seqEditF3.setObjectName("seqEditF3")
        self.gridLayout_4.addWidget(self.seqEditF3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.seqEditF4 = QtWidgets.QTextEdit(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(15)
        self.seqEditF4.setFont(font)
        self.seqEditF4.setLineWidth(1)
        self.seqEditF4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.seqEditF4.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.seqEditF4.setLineWrapColumnOrWidth(0)
        self.seqEditF4.setObjectName("seqEditF4")
        self.gridLayout_5.addWidget(self.seqEditF4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 2, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.confirmButton = QtWidgets.QPushButton(GibsonMSADialog)
        self.confirmButton.setCheckable(True)
        self.confirmButton.setChecked(True)
        self.confirmButton.setObjectName("confirmButton")
        self.horizontalLayout.addWidget(self.confirmButton)
        self.cancelButton = QtWidgets.QPushButton(GibsonMSADialog)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(GibsonMSADialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.notice = QtWidgets.QLabel(GibsonMSADialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.notice.setFont(font)
        self.notice.setObjectName("notice")
        self.gridLayout.addWidget(self.notice, 2, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioAA = QtWidgets.QRadioButton(GibsonMSADialog)
        self.radioAA.setChecked(True)
        self.radioAA.setObjectName("radioAA")
        self.horizontalLayout_2.addWidget(self.radioAA)
        self.radioNT = QtWidgets.QRadioButton(GibsonMSADialog)
        self.radioNT.setObjectName("radioNT")
        self.horizontalLayout_2.addWidget(self.radioNT)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)

        self.retranslateUi(GibsonMSADialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(GibsonMSADialog)

    def retranslateUi(self, GibsonMSADialog):
        _translate = QtCore.QCoreApplication.translate
        GibsonMSADialog.setWindowTitle(_translate("GibsonMSADialog", "Review and Confirm all fragments"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("GibsonMSADialog", "Fragment 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("GibsonMSADialog", "Fragment 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("GibsonMSADialog", "Fragment 3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("GibsonMSADialog", "Fragment 4"))
        self.confirmButton.setText(_translate("GibsonMSADialog", "Confirm"))
        self.cancelButton.setText(_translate("GibsonMSADialog", "Cancel"))
        self.label.setText(_translate("GibsonMSADialog", "Please review Gibson Fragments Design:"))
        self.notice.setText(_translate("GibsonMSADialog", "\'-\' in sequences will be removed before generating Fragments"))
        self.radioAA.setText(_translate("GibsonMSADialog", "Amino Acid"))
        self.radioNT.setText(_translate("GibsonMSADialog", "Nucleotide"))
