# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gibsonclone.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_gibsoncloneDialog(object):
    def setupUi(self, gibsoncloneDialog):
        gibsoncloneDialog.setObjectName("gibsoncloneDialog")
        gibsoncloneDialog.resize(688, 707)
        self.label = QtWidgets.QLabel(gibsoncloneDialog)
        self.label.setGeometry(QtCore.QRect(120, 20, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(gibsoncloneDialog)
        self.label_2.setGeometry(QtCore.QRect(50, 60, 131, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(gibsoncloneDialog)
        self.label_3.setGeometry(QtCore.QRect(50, 270, 581, 21))
        self.label_3.setObjectName("label_3")
        self.jointUP = QtWidgets.QTextEdit(gibsoncloneDialog)
        self.jointUP.setGeometry(QtCore.QRect(50, 300, 581, 51))
        self.jointUP.setObjectName("jointUP")
        self.jointDOWN = QtWidgets.QTextEdit(gibsoncloneDialog)
        self.jointDOWN.setGeometry(QtCore.QRect(50, 390, 581, 51))
        self.jointDOWN.setObjectName("jointDOWN")
        self.label_4 = QtWidgets.QLabel(gibsoncloneDialog)
        self.label_4.setGeometry(QtCore.QRect(50, 580, 581, 21))
        self.label_4.setObjectName("label_4")
        self.outpath = QtWidgets.QLineEdit(gibsoncloneDialog)
        self.outpath.setGeometry(QtCore.QRect(50, 610, 491, 31))
        self.outpath.setObjectName("outpath")
        self.browse = QtWidgets.QPushButton(gibsoncloneDialog)
        self.browse.setGeometry(QtCore.QRect(540, 610, 91, 31))
        self.browse.setObjectName("browse")
        self.horizontalLayoutWidget = QtWidgets.QWidget(gibsoncloneDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 650, 581, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.yes = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.yes.setDefault(True)
        self.yes.setObjectName("yes")
        self.horizontalLayout.addWidget(self.yes)
        self.cancel = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.cancel.setObjectName("cancel")
        self.horizontalLayout.addWidget(self.cancel)
        self.label_5 = QtWidgets.QLabel(gibsoncloneDialog)
        self.label_5.setGeometry(QtCore.QRect(50, 360, 581, 21))
        self.label_5.setObjectName("label_5")
        self.selection = QtWidgets.QListWidget(gibsoncloneDialog)
        self.selection.setGeometry(QtCore.QRect(50, 80, 581, 181))
        self.selection.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.selection.setObjectName("selection")
        self.label_6 = QtWidgets.QLabel(gibsoncloneDialog)
        self.label_6.setGeometry(QtCore.QRect(50, 450, 581, 21))
        self.label_6.setObjectName("label_6")
        self.tabWidget = QtWidgets.QTabWidget(gibsoncloneDialog)
        self.tabWidget.setGeometry(QtCore.QRect(50, 470, 581, 111))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.dbpath = QtWidgets.QLineEdit(self.tab)
        self.dbpath.setGeometry(QtCore.QRect(0, 30, 381, 31))
        self.dbpath.setObjectName("dbpath")
        self.createDB = QtWidgets.QPushButton(self.tab)
        self.createDB.setGeometry(QtCore.QRect(390, 30, 91, 31))
        self.createDB.setObjectName("createDB")
        self.browseDB = QtWidgets.QPushButton(self.tab)
        self.browseDB.setGeometry(QtCore.QRect(480, 30, 91, 31))
        self.browseDB.setObjectName("browseDB")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(10, 50, 79, 25))
        self.label_8.setObjectName("label_8")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(10, 0, 79, 59))
        self.label_7.setObjectName("label_7")
        self.Userinput = QtWidgets.QLineEdit(self.tab_2)
        self.Userinput.setGeometry(QtCore.QRect(90, 50, 199, 21))
        self.Userinput.setObjectName("Userinput")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(390, 10, 61, 41))
        self.label_9.setObjectName("label_9")
        self.DBnameinput = QtWidgets.QLineEdit(self.tab_2)
        self.DBnameinput.setGeometry(QtCore.QRect(458, 20, 111, 21))
        self.DBnameinput.setObjectName("DBnameinput")
        self.Passinput = QtWidgets.QLineEdit(self.tab_2)
        self.Passinput.setGeometry(QtCore.QRect(370, 50, 199, 21))
        self.Passinput.setObjectName("Passinput")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(300, 50, 79, 25))
        self.label_10.setObjectName("label_10")
        self.IPinput = QtWidgets.QLineEdit(self.tab_2)
        self.IPinput.setGeometry(QtCore.QRect(90, 20, 199, 21))
        self.IPinput.setObjectName("IPinput")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(300, 10, 31, 41))
        self.label_11.setObjectName("label_11")
        self.Portinput = QtWidgets.QLineEdit(self.tab_2)
        self.Portinput.setGeometry(QtCore.QRect(330, 20, 51, 21))
        self.Portinput.setObjectName("Portinput")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(gibsoncloneDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(gibsoncloneDialog)

    def retranslateUi(self, gibsoncloneDialog):
        _translate = QtCore.QCoreApplication.translate
        gibsoncloneDialog.setWindowTitle(_translate("gibsoncloneDialog", "Gibson Clone Fragments Design"))
        self.label.setText(_translate("gibsoncloneDialog", "Welcome to Gibson Clone Fragment Desgin page!"))
        self.label_2.setText(_translate("gibsoncloneDialog", "Your selections:"))
        self.label_3.setText(_translate("gibsoncloneDialog", "Joint region for upstream end  (Gibson cloning into the vector):"))
        self.label_4.setText(_translate("gibsoncloneDialog", "Gibson clone fragments files output path:"))
        self.browse.setText(_translate("gibsoncloneDialog", "Browse"))
        self.yes.setText(_translate("gibsoncloneDialog", "Generate Fragments"))
        self.cancel.setText(_translate("gibsoncloneDialog", "Cancel"))
        self.label_5.setText(_translate("gibsoncloneDialog", "Joint region for 3\' end  (instead of transmembrane region):"))
        self.label_6.setText(_translate("gibsoncloneDialog", "Fragments Database:"))
        self.createDB.setText(_translate("gibsoncloneDialog", "Create"))
        self.browseDB.setText(_translate("gibsoncloneDialog", "Browse"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("gibsoncloneDialog", "Loacl DB"))
        self.label_8.setText(_translate("gibsoncloneDialog", "User Name"))
        self.label_7.setText(_translate("gibsoncloneDialog", "Server IP"))
        self.label_9.setText(_translate("gibsoncloneDialog", "DB name"))
        self.label_10.setText(_translate("gibsoncloneDialog", "Password"))
        self.label_11.setText(_translate("gibsoncloneDialog", "Port"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("gibsoncloneDialog", "Online DB"))


