# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jointdialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JointDialog(object):
    def setupUi(self, JointDialog):
        JointDialog.setObjectName("JointDialog")
        JointDialog.resize(472, 609)
        self.gridLayout_2 = QtWidgets.QGridLayout(JointDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(JointDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.H1_user_GB = QtWidgets.QGroupBox(self.tab)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.H1_user_GB.setFont(font)
        self.H1_user_GB.setObjectName("H1_user_GB")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.H1_user_GB)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_16 = QtWidgets.QLabel(self.H1_user_GB)
        self.label_16.setObjectName("label_16")
        self.gridLayout_6.addWidget(self.label_16, 0, 2, 1, 1)
        self.H1_F1_EU = QtWidgets.QLineEdit(self.H1_user_GB)
        self.H1_F1_EU.setObjectName("H1_F1_EU")
        self.gridLayout_6.addWidget(self.H1_F1_EU, 0, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.H1_user_GB)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 0, 0, 1, 1)
        self.H1_F2_SU = QtWidgets.QLineEdit(self.H1_user_GB)
        self.H1_F2_SU.setObjectName("H1_F2_SU")
        self.gridLayout_6.addWidget(self.H1_F2_SU, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.H1_user_GB)
        self.label_11.setObjectName("label_11")
        self.gridLayout_6.addWidget(self.label_11, 2, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.H1_user_GB)
        self.label_14.setObjectName("label_14")
        self.gridLayout_6.addWidget(self.label_14, 2, 0, 1, 1)
        self.H1_F2_EU = QtWidgets.QLineEdit(self.H1_user_GB)
        self.H1_F2_EU.setObjectName("H1_F2_EU")
        self.gridLayout_6.addWidget(self.H1_F2_EU, 1, 3, 1, 1)
        self.H1_F3_EU = QtWidgets.QLineEdit(self.H1_user_GB)
        self.H1_F3_EU.setObjectName("H1_F3_EU")
        self.gridLayout_6.addWidget(self.H1_F3_EU, 2, 3, 1, 1)
        self.H1_F3_SU = QtWidgets.QLineEdit(self.H1_user_GB)
        self.H1_F3_SU.setObjectName("H1_F3_SU")
        self.gridLayout_6.addWidget(self.H1_F3_SU, 2, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.H1_user_GB)
        self.label_17.setObjectName("label_17")
        self.gridLayout_6.addWidget(self.label_17, 3, 0, 1, 1)
        self.H1_F1_SU = QtWidgets.QLineEdit(self.H1_user_GB)
        self.H1_F1_SU.setObjectName("H1_F1_SU")
        self.gridLayout_6.addWidget(self.H1_F1_SU, 0, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.H1_user_GB)
        self.label_13.setObjectName("label_13")
        self.gridLayout_6.addWidget(self.label_13, 1, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.H1_user_GB)
        self.label_15.setObjectName("label_15")
        self.gridLayout_6.addWidget(self.label_15, 1, 2, 1, 1)
        self.H1_F4_EU = QtWidgets.QLineEdit(self.H1_user_GB)
        self.H1_F4_EU.setObjectName("H1_F4_EU")
        self.gridLayout_6.addWidget(self.H1_F4_EU, 3, 3, 1, 1)
        self.H1_F4_SU = QtWidgets.QLineEdit(self.H1_user_GB)
        self.H1_F4_SU.setObjectName("H1_F4_SU")
        self.gridLayout_6.addWidget(self.H1_F4_SU, 3, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.H1_user_GB)
        self.label_12.setObjectName("label_12")
        self.gridLayout_6.addWidget(self.label_12, 3, 2, 1, 1)
        self.gridLayout.addWidget(self.H1_user_GB, 1, 0, 1, 1)
        self.H1_default_GB = QtWidgets.QGroupBox(self.tab)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.H1_default_GB.setFont(font)
        self.H1_default_GB.setObjectName("H1_default_GB")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.H1_default_GB)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.H1_F3_E = QtWidgets.QLineEdit(self.H1_default_GB)
        self.H1_F3_E.setReadOnly(True)
        self.H1_F3_E.setObjectName("H1_F3_E")
        self.gridLayout_5.addWidget(self.H1_F3_E, 2, 3, 1, 1)
        self.H1_F1_S = QtWidgets.QLineEdit(self.H1_default_GB)
        self.H1_F1_S.setReadOnly(True)
        self.H1_F1_S.setObjectName("H1_F1_S")
        self.gridLayout_5.addWidget(self.H1_F1_S, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.H1_default_GB)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 0, 2, 1, 1)
        self.H1_F4_E = QtWidgets.QLineEdit(self.H1_default_GB)
        self.H1_F4_E.setReadOnly(True)
        self.H1_F4_E.setObjectName("H1_F4_E")
        self.gridLayout_5.addWidget(self.H1_F4_E, 3, 3, 1, 1)
        self.H1_F2_E = QtWidgets.QLineEdit(self.H1_default_GB)
        self.H1_F2_E.setReadOnly(True)
        self.H1_F2_E.setObjectName("H1_F2_E")
        self.gridLayout_5.addWidget(self.H1_F2_E, 1, 3, 1, 1)
        self.H1_F2_S = QtWidgets.QLineEdit(self.H1_default_GB)
        self.H1_F2_S.setReadOnly(True)
        self.H1_F2_S.setObjectName("H1_F2_S")
        self.gridLayout_5.addWidget(self.H1_F2_S, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.H1_default_GB)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 1, 2, 1, 1)
        self.H1_F4_S = QtWidgets.QLineEdit(self.H1_default_GB)
        self.H1_F4_S.setReadOnly(True)
        self.H1_F4_S.setObjectName("H1_F4_S")
        self.gridLayout_5.addWidget(self.H1_F4_S, 3, 1, 1, 1)
        self.H1_F3_S = QtWidgets.QLineEdit(self.H1_default_GB)
        self.H1_F3_S.setReadOnly(True)
        self.H1_F3_S.setObjectName("H1_F3_S")
        self.gridLayout_5.addWidget(self.H1_F3_S, 2, 1, 1, 1)
        self.H1_F1_E = QtWidgets.QLineEdit(self.H1_default_GB)
        self.H1_F1_E.setReadOnly(True)
        self.H1_F1_E.setObjectName("H1_F1_E")
        self.gridLayout_5.addWidget(self.H1_F1_E, 0, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.H1_default_GB)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 3, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.H1_default_GB)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.H1_default_GB)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 2, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.H1_default_GB)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.H1_default_GB)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.H1_default_GB)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.H1_default_GB, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.H3_default_GB = QtWidgets.QGroupBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.H3_default_GB.setFont(font)
        self.H3_default_GB.setObjectName("H3_default_GB")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.H3_default_GB)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_18 = QtWidgets.QLabel(self.H3_default_GB)
        self.label_18.setObjectName("label_18")
        self.gridLayout_7.addWidget(self.label_18, 0, 0, 1, 1)
        self.H3_F1_S = QtWidgets.QLineEdit(self.H3_default_GB)
        self.H3_F1_S.setReadOnly(True)
        self.H3_F1_S.setObjectName("H3_F1_S")
        self.gridLayout_7.addWidget(self.H3_F1_S, 0, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.H3_default_GB)
        self.label_24.setObjectName("label_24")
        self.gridLayout_7.addWidget(self.label_24, 0, 2, 1, 1)
        self.H3_F1_E = QtWidgets.QLineEdit(self.H3_default_GB)
        self.H3_F1_E.setReadOnly(True)
        self.H3_F1_E.setObjectName("H3_F1_E")
        self.gridLayout_7.addWidget(self.H3_F1_E, 0, 3, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.H3_default_GB)
        self.label_21.setObjectName("label_21")
        self.gridLayout_7.addWidget(self.label_21, 1, 0, 1, 1)
        self.H3_F2_S = QtWidgets.QLineEdit(self.H3_default_GB)
        self.H3_F2_S.setReadOnly(True)
        self.H3_F2_S.setObjectName("H3_F2_S")
        self.gridLayout_7.addWidget(self.H3_F2_S, 1, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.H3_default_GB)
        self.label_23.setObjectName("label_23")
        self.gridLayout_7.addWidget(self.label_23, 1, 2, 1, 1)
        self.H3_F2_E = QtWidgets.QLineEdit(self.H3_default_GB)
        self.H3_F2_E.setReadOnly(True)
        self.H3_F2_E.setObjectName("H3_F2_E")
        self.gridLayout_7.addWidget(self.H3_F2_E, 1, 3, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.H3_default_GB)
        self.label_22.setObjectName("label_22")
        self.gridLayout_7.addWidget(self.label_22, 2, 0, 1, 1)
        self.H3_F3_S = QtWidgets.QLineEdit(self.H3_default_GB)
        self.H3_F3_S.setReadOnly(True)
        self.H3_F3_S.setObjectName("H3_F3_S")
        self.gridLayout_7.addWidget(self.H3_F3_S, 2, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.H3_default_GB)
        self.label_19.setObjectName("label_19")
        self.gridLayout_7.addWidget(self.label_19, 2, 2, 1, 1)
        self.H3_F3_E = QtWidgets.QLineEdit(self.H3_default_GB)
        self.H3_F3_E.setReadOnly(True)
        self.H3_F3_E.setObjectName("H3_F3_E")
        self.gridLayout_7.addWidget(self.H3_F3_E, 2, 3, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.H3_default_GB)
        self.label_25.setObjectName("label_25")
        self.gridLayout_7.addWidget(self.label_25, 3, 0, 1, 1)
        self.H3_F4_S = QtWidgets.QLineEdit(self.H3_default_GB)
        self.H3_F4_S.setReadOnly(True)
        self.H3_F4_S.setObjectName("H3_F4_S")
        self.gridLayout_7.addWidget(self.H3_F4_S, 3, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.H3_default_GB)
        self.label_20.setObjectName("label_20")
        self.gridLayout_7.addWidget(self.label_20, 3, 2, 1, 1)
        self.H3_F4_E = QtWidgets.QLineEdit(self.H3_default_GB)
        self.H3_F4_E.setReadOnly(True)
        self.H3_F4_E.setObjectName("H3_F4_E")
        self.gridLayout_7.addWidget(self.H3_F4_E, 3, 3, 1, 1)
        self.gridLayout_3.addWidget(self.H3_default_GB, 0, 0, 1, 1)
        self.H3_user_GB = QtWidgets.QGroupBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.H3_user_GB.setFont(font)
        self.H3_user_GB.setObjectName("H3_user_GB")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.H3_user_GB)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_26 = QtWidgets.QLabel(self.H3_user_GB)
        self.label_26.setObjectName("label_26")
        self.gridLayout_8.addWidget(self.label_26, 0, 0, 1, 1)
        self.H3_F1_SU = QtWidgets.QLineEdit(self.H3_user_GB)
        self.H3_F1_SU.setObjectName("H3_F1_SU")
        self.gridLayout_8.addWidget(self.H3_F1_SU, 0, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.H3_user_GB)
        self.label_32.setObjectName("label_32")
        self.gridLayout_8.addWidget(self.label_32, 0, 2, 1, 1)
        self.H3_F1_EU = QtWidgets.QLineEdit(self.H3_user_GB)
        self.H3_F1_EU.setObjectName("H3_F1_EU")
        self.gridLayout_8.addWidget(self.H3_F1_EU, 0, 3, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.H3_user_GB)
        self.label_29.setObjectName("label_29")
        self.gridLayout_8.addWidget(self.label_29, 1, 0, 1, 1)
        self.H3_F2_SU = QtWidgets.QLineEdit(self.H3_user_GB)
        self.H3_F2_SU.setObjectName("H3_F2_SU")
        self.gridLayout_8.addWidget(self.H3_F2_SU, 1, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.H3_user_GB)
        self.label_31.setObjectName("label_31")
        self.gridLayout_8.addWidget(self.label_31, 1, 2, 1, 1)
        self.H3_F2_EU = QtWidgets.QLineEdit(self.H3_user_GB)
        self.H3_F2_EU.setObjectName("H3_F2_EU")
        self.gridLayout_8.addWidget(self.H3_F2_EU, 1, 3, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.H3_user_GB)
        self.label_30.setObjectName("label_30")
        self.gridLayout_8.addWidget(self.label_30, 2, 0, 1, 1)
        self.H3_F3_SU = QtWidgets.QLineEdit(self.H3_user_GB)
        self.H3_F3_SU.setObjectName("H3_F3_SU")
        self.gridLayout_8.addWidget(self.H3_F3_SU, 2, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.H3_user_GB)
        self.label_27.setObjectName("label_27")
        self.gridLayout_8.addWidget(self.label_27, 2, 2, 1, 1)
        self.H3_F3_EU = QtWidgets.QLineEdit(self.H3_user_GB)
        self.H3_F3_EU.setObjectName("H3_F3_EU")
        self.gridLayout_8.addWidget(self.H3_F3_EU, 2, 3, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.H3_user_GB)
        self.label_33.setObjectName("label_33")
        self.gridLayout_8.addWidget(self.label_33, 3, 0, 1, 1)
        self.H3_F4_SU = QtWidgets.QLineEdit(self.H3_user_GB)
        self.H3_F4_SU.setObjectName("H3_F4_SU")
        self.gridLayout_8.addWidget(self.H3_F4_SU, 3, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.H3_user_GB)
        self.label_28.setObjectName("label_28")
        self.gridLayout_8.addWidget(self.label_28, 3, 2, 1, 1)
        self.H3_F4_EU = QtWidgets.QLineEdit(self.H3_user_GB)
        self.H3_F4_EU.setObjectName("H3_F4_EU")
        self.gridLayout_8.addWidget(self.H3_F4_EU, 3, 3, 1, 1)
        self.gridLayout_3.addWidget(self.H3_user_GB, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.NA_default_GB = QtWidgets.QGroupBox(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.NA_default_GB.setFont(font)
        self.NA_default_GB.setObjectName("NA_default_GB")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.NA_default_GB)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_34 = QtWidgets.QLabel(self.NA_default_GB)
        self.label_34.setObjectName("label_34")
        self.gridLayout_9.addWidget(self.label_34, 0, 0, 1, 1)
        self.NA_F1_S = QtWidgets.QLineEdit(self.NA_default_GB)
        self.NA_F1_S.setReadOnly(True)
        self.NA_F1_S.setObjectName("NA_F1_S")
        self.gridLayout_9.addWidget(self.NA_F1_S, 0, 1, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.NA_default_GB)
        self.label_40.setObjectName("label_40")
        self.gridLayout_9.addWidget(self.label_40, 0, 2, 1, 1)
        self.NA_F1_E = QtWidgets.QLineEdit(self.NA_default_GB)
        self.NA_F1_E.setReadOnly(True)
        self.NA_F1_E.setObjectName("NA_F1_E")
        self.gridLayout_9.addWidget(self.NA_F1_E, 0, 3, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.NA_default_GB)
        self.label_37.setObjectName("label_37")
        self.gridLayout_9.addWidget(self.label_37, 1, 0, 1, 1)
        self.NA_F2_S = QtWidgets.QLineEdit(self.NA_default_GB)
        self.NA_F2_S.setReadOnly(True)
        self.NA_F2_S.setObjectName("NA_F2_S")
        self.gridLayout_9.addWidget(self.NA_F2_S, 1, 1, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.NA_default_GB)
        self.label_39.setObjectName("label_39")
        self.gridLayout_9.addWidget(self.label_39, 1, 2, 1, 1)
        self.NA_F2_E = QtWidgets.QLineEdit(self.NA_default_GB)
        self.NA_F2_E.setReadOnly(True)
        self.NA_F2_E.setObjectName("NA_F2_E")
        self.gridLayout_9.addWidget(self.NA_F2_E, 1, 3, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.NA_default_GB)
        self.label_38.setObjectName("label_38")
        self.gridLayout_9.addWidget(self.label_38, 2, 0, 1, 1)
        self.NA_F3_S = QtWidgets.QLineEdit(self.NA_default_GB)
        self.NA_F3_S.setReadOnly(True)
        self.NA_F3_S.setObjectName("NA_F3_S")
        self.gridLayout_9.addWidget(self.NA_F3_S, 2, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.NA_default_GB)
        self.label_35.setObjectName("label_35")
        self.gridLayout_9.addWidget(self.label_35, 2, 2, 1, 1)
        self.NA_F3_E = QtWidgets.QLineEdit(self.NA_default_GB)
        self.NA_F3_E.setReadOnly(True)
        self.NA_F3_E.setObjectName("NA_F3_E")
        self.gridLayout_9.addWidget(self.NA_F3_E, 2, 3, 1, 1)
        self.gridLayout_4.addWidget(self.NA_default_GB, 0, 0, 1, 1)
        self.NA_user_GB = QtWidgets.QGroupBox(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.NA_user_GB.setFont(font)
        self.NA_user_GB.setObjectName("NA_user_GB")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.NA_user_GB)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_36 = QtWidgets.QLabel(self.NA_user_GB)
        self.label_36.setObjectName("label_36")
        self.gridLayout_10.addWidget(self.label_36, 0, 0, 1, 1)
        self.NA_F1_SU = QtWidgets.QLineEdit(self.NA_user_GB)
        self.NA_F1_SU.setObjectName("NA_F1_SU")
        self.gridLayout_10.addWidget(self.NA_F1_SU, 0, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.NA_user_GB)
        self.label_43.setObjectName("label_43")
        self.gridLayout_10.addWidget(self.label_43, 0, 2, 1, 1)
        self.NA_F1_EU = QtWidgets.QLineEdit(self.NA_user_GB)
        self.NA_F1_EU.setObjectName("NA_F1_EU")
        self.gridLayout_10.addWidget(self.NA_F1_EU, 0, 3, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.NA_user_GB)
        self.label_42.setObjectName("label_42")
        self.gridLayout_10.addWidget(self.label_42, 1, 0, 1, 1)
        self.NA_F2_SU = QtWidgets.QLineEdit(self.NA_user_GB)
        self.NA_F2_SU.setObjectName("NA_F2_SU")
        self.gridLayout_10.addWidget(self.NA_F2_SU, 1, 1, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.NA_user_GB)
        self.label_41.setObjectName("label_41")
        self.gridLayout_10.addWidget(self.label_41, 1, 2, 1, 1)
        self.NA_F2_EU = QtWidgets.QLineEdit(self.NA_user_GB)
        self.NA_F2_EU.setObjectName("NA_F2_EU")
        self.gridLayout_10.addWidget(self.NA_F2_EU, 1, 3, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.NA_user_GB)
        self.label_45.setObjectName("label_45")
        self.gridLayout_10.addWidget(self.label_45, 2, 0, 1, 1)
        self.NA_F3_SU = QtWidgets.QLineEdit(self.NA_user_GB)
        self.NA_F3_SU.setObjectName("NA_F3_SU")
        self.gridLayout_10.addWidget(self.NA_F3_SU, 2, 1, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.NA_user_GB)
        self.label_44.setObjectName("label_44")
        self.gridLayout_10.addWidget(self.label_44, 2, 2, 1, 1)
        self.NA_F3_EU = QtWidgets.QLineEdit(self.NA_user_GB)
        self.NA_F3_EU.setObjectName("NA_F3_EU")
        self.gridLayout_10.addWidget(self.NA_F3_EU, 2, 3, 1, 1)
        self.gridLayout_4.addWidget(self.NA_user_GB, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout_2.addWidget(self.tabWidget, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(JointDialog)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.saveButton = QtWidgets.QPushButton(JointDialog)
        self.saveButton.setCheckable(True)
        self.saveButton.setChecked(True)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.exitButton = QtWidgets.QPushButton(JointDialog)
        self.exitButton.setObjectName("exitButton")
        self.horizontalLayout.addWidget(self.exitButton)
        self.cancelButton = QtWidgets.QPushButton(JointDialog)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.gridLayout_2.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.label_46 = QtWidgets.QLabel(JointDialog)
        self.label_46.setObjectName("label_46")
        self.gridLayout_2.addWidget(self.label_46, 1, 0, 1, 1)

        self.retranslateUi(JointDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(JointDialog)

    def retranslateUi(self, JointDialog):
        _translate = QtCore.QCoreApplication.translate
        JointDialog.setWindowTitle(_translate("JointDialog", "Review Current joint region setting for Gibson Clones"))
        self.H1_user_GB.setTitle(_translate("JointDialog", "User Define Seeting"))
        self.label_16.setText(_translate("JointDialog", "to"))
        self.label_10.setText(_translate("JointDialog", "Fragment1"))
        self.label_11.setText(_translate("JointDialog", "to"))
        self.label_14.setText(_translate("JointDialog", "Fragment3"))
        self.label_17.setText(_translate("JointDialog", "Fragment4"))
        self.label_13.setText(_translate("JointDialog", "Fragment2"))
        self.label_15.setText(_translate("JointDialog", "to"))
        self.label_12.setText(_translate("JointDialog", "to"))
        self.H1_default_GB.setTitle(_translate("JointDialog", "Default Setting"))
        self.label_2.setText(_translate("JointDialog", "to"))
        self.label_3.setText(_translate("JointDialog", "to"))
        self.label_5.setText(_translate("JointDialog", "to"))
        self.label_9.setText(_translate("JointDialog", "Fragment4"))
        self.label_4.setText(_translate("JointDialog", "to"))
        self.label_8.setText(_translate("JointDialog", "Fragment3"))
        self.label_6.setText(_translate("JointDialog", "Fragment1"))
        self.label_7.setText(_translate("JointDialog", "Fragment2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("JointDialog", "H1/Group1 HA"))
        self.H3_default_GB.setTitle(_translate("JointDialog", "Default Setting"))
        self.label_18.setText(_translate("JointDialog", "Fragment1"))
        self.label_24.setText(_translate("JointDialog", "to"))
        self.label_21.setText(_translate("JointDialog", "Fragment2"))
        self.label_23.setText(_translate("JointDialog", "to"))
        self.label_22.setText(_translate("JointDialog", "Fragment3"))
        self.label_19.setText(_translate("JointDialog", "to"))
        self.label_25.setText(_translate("JointDialog", "Fragment4"))
        self.label_20.setText(_translate("JointDialog", "to"))
        self.H3_user_GB.setTitle(_translate("JointDialog", "User Define Seeting"))
        self.label_26.setText(_translate("JointDialog", "Fragment1"))
        self.label_32.setText(_translate("JointDialog", "to"))
        self.label_29.setText(_translate("JointDialog", "Fragment2"))
        self.label_31.setText(_translate("JointDialog", "to"))
        self.label_30.setText(_translate("JointDialog", "Fragment3"))
        self.label_27.setText(_translate("JointDialog", "to"))
        self.label_33.setText(_translate("JointDialog", "Fragment4"))
        self.label_28.setText(_translate("JointDialog", "to"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("JointDialog", "H3/Group2 HA"))
        self.NA_default_GB.setTitle(_translate("JointDialog", "Default Setting"))
        self.label_34.setText(_translate("JointDialog", "Fragment1"))
        self.label_40.setText(_translate("JointDialog", "to"))
        self.label_37.setText(_translate("JointDialog", "Fragment2"))
        self.label_39.setText(_translate("JointDialog", "to"))
        self.label_38.setText(_translate("JointDialog", "Fragment3"))
        self.label_35.setText(_translate("JointDialog", "to"))
        self.NA_user_GB.setTitle(_translate("JointDialog", "User Define Seeting"))
        self.label_36.setText(_translate("JointDialog", "Fragment1"))
        self.label_43.setText(_translate("JointDialog", "to"))
        self.label_42.setText(_translate("JointDialog", "Fragment2"))
        self.label_41.setText(_translate("JointDialog", "to"))
        self.label_45.setText(_translate("JointDialog", "Fragment3"))
        self.label_44.setText(_translate("JointDialog", "to"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("JointDialog", "NA"))
        self.label.setText(_translate("JointDialog", "Review Current joint region setting for Gibson Clones"))
        self.saveButton.setText(_translate("JointDialog", "Save"))
        self.exitButton.setText(_translate("JointDialog", "Exit without save"))
        self.cancelButton.setText(_translate("JointDialog", "Cancel"))
        self.label_46.setText(_translate("JointDialog", "Please fill all inputs if you want to setup your own joint region design!"))
