# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainLibrator_UI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainLibrator(object):
    def setupUi(self, MainLibrator):
        MainLibrator.setObjectName("MainLibrator")
        MainLibrator.resize(1104, 1175)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainLibrator.sizePolicy().hasHeightForWidth())
        MainLibrator.setSizePolicy(sizePolicy)
        MainLibrator.setMinimumSize(QtCore.QSize(0, 75))
        MainLibrator.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainLibrator.setAnimated(False)
        MainLibrator.setDocumentMode(False)
        MainLibrator.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainLibrator)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_11 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_11.sizePolicy().hasHeightForWidth())
        self.frame_11.setSizePolicy(sizePolicy)
        self.frame_11.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_11.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_9.setContentsMargins(-1, 3, -1, 3)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.line = QtWidgets.QFrame(self.frame_11)
        self.line.setMinimumSize(QtCore.QSize(0, 60))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_9.addWidget(self.line, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_11)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_4.setObjectName("label_4")
        self.gridLayout_9.addWidget(self.label_4, 0, 2, 1, 1)
        self.gibsonBTN = QtWidgets.QPushButton(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gibsonBTN.sizePolicy().hasHeightForWidth())
        self.gibsonBTN.setSizePolicy(sizePolicy)
        self.gibsonBTN.setMinimumSize(QtCore.QSize(0, 20))
        self.gibsonBTN.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.gibsonBTN.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/PNG-Icons/GibsonClone.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gibsonBTN.setIcon(icon)
        self.gibsonBTN.setIconSize(QtCore.QSize(40, 40))
        self.gibsonBTN.setObjectName("gibsonBTN")
        self.gridLayout_9.addWidget(self.gibsonBTN, 0, 5, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.frame_11)
        self.line_3.setMinimumSize(QtCore.QSize(0, 60))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_9.addWidget(self.line_3, 0, 4, 1, 1)
        self.pymolBTN = QtWidgets.QPushButton(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pymolBTN.sizePolicy().hasHeightForWidth())
        self.pymolBTN.setSizePolicy(sizePolicy)
        self.pymolBTN.setMinimumSize(QtCore.QSize(0, 20))
        self.pymolBTN.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pymolBTN.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/PNG-Icons/PyMOL.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pymolBTN.setIcon(icon1)
        self.pymolBTN.setIconSize(QtCore.QSize(40, 40))
        self.pymolBTN.setObjectName("pymolBTN")
        self.gridLayout_9.addWidget(self.pymolBTN, 0, 0, 1, 1)
        self.lblBaseName = QtWidgets.QTextEdit(self.frame_11)
        self.lblBaseName.setMinimumSize(QtCore.QSize(0, 30))
        self.lblBaseName.setMaximumSize(QtCore.QSize(16777215, 50))
        self.lblBaseName.setReadOnly(True)
        self.lblBaseName.setObjectName("lblBaseName")
        self.gridLayout_9.addWidget(self.lblBaseName, 0, 3, 1, 1)
        self.gridLayout_2.addWidget(self.frame_11, 3, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setAcceptDrops(False)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tabMain = QtWidgets.QWidget()
        self.tabMain.setObjectName("tabMain")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tabMain)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_7 = QtWidgets.QFrame(self.tabMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 34))
        self.frame_7.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_7)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.cboRecent = QtWidgets.QComboBox(self.frame_7)
        self.cboRecent.setMinimumSize(QtCore.QSize(255, 0))
        self.cboRecent.setObjectName("cboRecent")
        self.cboRecent.addItem("")
        self.horizontalLayout_2.addWidget(self.cboRecent)
        self.line_6 = QtWidgets.QFrame(self.frame_7)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_2.addWidget(self.line_6)
        self.btnCopyRecords = QtWidgets.QPushButton(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCopyRecords.sizePolicy().hasHeightForWidth())
        self.btnCopyRecords.setSizePolicy(sizePolicy)
        self.btnCopyRecords.setMinimumSize(QtCore.QSize(0, 0))
        self.btnCopyRecords.setMaximumSize(QtCore.QSize(50, 50))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/PNG-Icons/Duplicate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCopyRecords.setIcon(icon2)
        self.btnCopyRecords.setIconSize(QtCore.QSize(24, 24))
        self.btnCopyRecords.setFlat(True)
        self.btnCopyRecords.setObjectName("btnCopyRecords")
        self.horizontalLayout_2.addWidget(self.btnCopyRecords)
        self.btnExtractRecords = QtWidgets.QPushButton(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnExtractRecords.sizePolicy().hasHeightForWidth())
        self.btnExtractRecords.setSizePolicy(sizePolicy)
        self.btnExtractRecords.setMinimumSize(QtCore.QSize(0, 0))
        self.btnExtractRecords.setMaximumSize(QtCore.QSize(40, 50))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/PNG-Icons/Insert.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnExtractRecords.setIcon(icon3)
        self.btnExtractRecords.setIconSize(QtCore.QSize(24, 24))
        self.btnExtractRecords.setFlat(True)
        self.btnExtractRecords.setObjectName("btnExtractRecords")
        self.horizontalLayout_2.addWidget(self.btnExtractRecords)
        self.line_5 = QtWidgets.QFrame(self.frame_7)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_2.addWidget(self.line_5)
        self.seqlabel_26 = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seqlabel_26.sizePolicy().hasHeightForWidth())
        self.seqlabel_26.setSizePolicy(sizePolicy)
        self.seqlabel_26.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(14)
        self.seqlabel_26.setFont(font)
        self.seqlabel_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.seqlabel_26.setObjectName("seqlabel_26")
        self.horizontalLayout_2.addWidget(self.seqlabel_26)
        self.cboReportOptions = QtWidgets.QComboBox(self.frame_7)
        self.cboReportOptions.setObjectName("cboReportOptions")
        self.cboReportOptions.addItem("")
        self.cboReportOptions.addItem("")
        self.cboReportOptions.addItem("")
        self.cboReportOptions.addItem("")
        self.cboReportOptions.addItem("")
        self.horizontalLayout_2.addWidget(self.cboReportOptions)
        self.verticalLayout.addWidget(self.frame_7)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tabMain)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1033, 1274))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame_13 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_13.sizePolicy().hasHeightForWidth())
        self.frame_13.setSizePolicy(sizePolicy)
        self.frame_13.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_16 = QtWidgets.QFrame(self.frame_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_16.sizePolicy().hasHeightForWidth())
        self.frame_16.setSizePolicy(sizePolicy)
        self.frame_16.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_16.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_16)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.spnFrom = QtWidgets.QSpinBox(self.frame_16)
        self.spnFrom.setMaximumSize(QtCore.QSize(70, 16777215))
        self.spnFrom.setMinimum(1)
        self.spnFrom.setMaximum(5000)
        self.spnFrom.setProperty("value", 1)
        self.spnFrom.setObjectName("spnFrom")
        self.gridLayout_13.addWidget(self.spnFrom, 1, 4, 1, 1)
        self.lblDNA = QtWidgets.QLabel(self.frame_16)
        self.lblDNA.setMinimumSize(QtCore.QSize(350, 0))
        self.lblDNA.setObjectName("lblDNA")
        self.gridLayout_13.addWidget(self.lblDNA, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem, 1, 1, 1, 1)
        self.seqlabel_9 = QtWidgets.QLabel(self.frame_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seqlabel_9.sizePolicy().hasHeightForWidth())
        self.seqlabel_9.setSizePolicy(sizePolicy)
        self.seqlabel_9.setMinimumSize(QtCore.QSize(0, 0))
        self.seqlabel_9.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(14)
        self.seqlabel_9.setFont(font)
        self.seqlabel_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.seqlabel_9.setObjectName("seqlabel_9")
        self.gridLayout_13.addWidget(self.seqlabel_9, 1, 3, 1, 1)
        self.btnReadingFrames = QtWidgets.QPushButton(self.frame_16)
        self.btnReadingFrames.setMaximumSize(QtCore.QSize(160, 16777215))
        self.btnReadingFrames.setObjectName("btnReadingFrames")
        self.gridLayout_13.addWidget(self.btnReadingFrames, 1, 7, 1, 1)
        self.seqlabel_10 = QtWidgets.QLabel(self.frame_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seqlabel_10.sizePolicy().hasHeightForWidth())
        self.seqlabel_10.setSizePolicy(sizePolicy)
        self.seqlabel_10.setMinimumSize(QtCore.QSize(0, 0))
        self.seqlabel_10.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(14)
        self.seqlabel_10.setFont(font)
        self.seqlabel_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.seqlabel_10.setObjectName("seqlabel_10")
        self.gridLayout_13.addWidget(self.seqlabel_10, 1, 2, 1, 1)
        self.seqlabel_19 = QtWidgets.QLabel(self.frame_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seqlabel_19.sizePolicy().hasHeightForWidth())
        self.seqlabel_19.setSizePolicy(sizePolicy)
        self.seqlabel_19.setMinimumSize(QtCore.QSize(0, 0))
        self.seqlabel_19.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(14)
        self.seqlabel_19.setFont(font)
        self.seqlabel_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.seqlabel_19.setObjectName("seqlabel_19")
        self.gridLayout_13.addWidget(self.seqlabel_19, 1, 5, 1, 1)
        self.spnTo = QtWidgets.QSpinBox(self.frame_16)
        self.spnTo.setMaximumSize(QtCore.QSize(70, 16777215))
        self.spnTo.setMinimum(1)
        self.spnTo.setMaximum(5000)
        self.spnTo.setProperty("value", 5000)
        self.spnTo.setObjectName("spnTo")
        self.gridLayout_13.addWidget(self.spnTo, 1, 6, 1, 1)
        self.verticalLayout_4.addWidget(self.frame_16)
        self.frame_3 = QtWidgets.QFrame(self.frame_13)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.SearchButton = QtWidgets.QCommandLinkButton(self.frame_3)
        self.SearchButton.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.SearchButton.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/PNG-Icons/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SearchButton.setIcon(icon4)
        self.SearchButton.setObjectName("SearchButton")
        self.gridLayout_8.addWidget(self.SearchButton, 0, 1, 1, 1)
        self.rdoAA = QtWidgets.QRadioButton(self.frame_3)
        self.rdoAA.setMaximumSize(QtCore.QSize(101, 16777215))
        self.rdoAA.setObjectName("rdoAA")
        self.gridLayout_8.addWidget(self.rdoAA, 0, 4, 1, 1)
        self.txtSearch = QtWidgets.QPlainTextEdit(self.frame_3)
        self.txtSearch.setMinimumSize(QtCore.QSize(0, 30))
        self.txtSearch.setMaximumSize(QtCore.QSize(16777215, 60))
        self.txtSearch.setObjectName("txtSearch")
        self.gridLayout_8.addWidget(self.txtSearch, 0, 2, 1, 1)
        self.rdoDNA = QtWidgets.QRadioButton(self.frame_3)
        self.rdoDNA.setMaximumSize(QtCore.QSize(56, 16777215))
        self.rdoDNA.setChecked(True)
        self.rdoDNA.setObjectName("rdoDNA")
        self.gridLayout_8.addWidget(self.rdoDNA, 0, 3, 1, 1)
        self.btnEditSequence = QtWidgets.QPushButton(self.frame_3)
        self.btnEditSequence.setObjectName("btnEditSequence")
        self.gridLayout_8.addWidget(self.btnEditSequence, 0, 5, 1, 1)
        self.verticalLayout_4.addWidget(self.frame_3)
        self.textSeq = QtWidgets.QTextEdit(self.frame_13)
        self.textSeq.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textSeq.setReadOnly(True)
        self.textSeq.setObjectName("textSeq")
        self.verticalLayout_4.addWidget(self.textSeq)
        self.lblAA = QtWidgets.QLabel(self.frame_13)
        self.lblAA.setObjectName("lblAA")
        self.verticalLayout_4.addWidget(self.lblAA)
        self.textAA = QtWidgets.QTextEdit(self.frame_13)
        self.textAA.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textAA.setReadOnly(True)
        self.textAA.setObjectName("textAA")
        self.verticalLayout_4.addWidget(self.textAA)
        self.gridLayout_6.addWidget(self.frame_13, 3, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_28 = QtWidgets.QLabel(self.frame_6)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_4.addWidget(self.label_28)
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        self.label_5.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.groupCombo = QtWidgets.QComboBox(self.frame_6)
        self.groupCombo.setObjectName("groupCombo")
        self.groupCombo.addItem("")
        self.groupCombo.addItem("")
        self.groupCombo.addItem("")
        self.horizontalLayout_4.addWidget(self.groupCombo)
        self.gridLayout_5.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_29 = QtWidgets.QLabel(self.frame_6)
        self.label_29.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_5.addWidget(self.label_29)
        self.btnDelete = QtWidgets.QPushButton(self.frame_6)
        self.btnDelete.setMaximumSize(QtCore.QSize(16777215, 20))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/PNG-Icons/bin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDelete.setIcon(icon5)
        self.btnDelete.setIconSize(QtCore.QSize(20, 20))
        self.btnDelete.setFlat(True)
        self.btnDelete.setObjectName("btnDelete")
        self.horizontalLayout_5.addWidget(self.btnDelete)
        self.gridLayout_5.addLayout(self.horizontalLayout_5, 0, 1, 1, 1)
        self.treeWidget = QtWidgets.QTreeWidget(self.frame_6)
        self.treeWidget.setMinimumSize(QtCore.QSize(0, 300))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.treeWidget.setFont(font)
        self.treeWidget.setHeaderHidden(True)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.gridLayout_5.addWidget(self.treeWidget, 1, 0, 1, 1)
        self.listWidgetStrainsIn = QtWidgets.QListWidget(self.frame_6)
        self.listWidgetStrainsIn.setMinimumSize(QtCore.QSize(0, 300))
        self.listWidgetStrainsIn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.listWidgetStrainsIn.setFont(font)
        self.listWidgetStrainsIn.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.listWidgetStrainsIn.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.listWidgetStrainsIn.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidgetStrainsIn.setMovement(QtWidgets.QListView.Free)
        self.listWidgetStrainsIn.setProperty("isWrapping", False)
        self.listWidgetStrainsIn.setWordWrap(True)
        self.listWidgetStrainsIn.setObjectName("listWidgetStrainsIn")
        self.gridLayout_5.addWidget(self.listWidgetStrainsIn, 1, 1, 1, 1)
        self.btnImport = QtWidgets.QPushButton(self.frame_6)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/PNG-Icons/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnImport.setIcon(icon6)
        self.btnImport.setFlat(True)
        self.btnImport.setObjectName("btnImport")
        self.gridLayout_5.addWidget(self.btnImport, 2, 0, 1, 1)
        self.btnClearAll = QtWidgets.QPushButton(self.frame_6)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/PNG-Icons/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnClearAll.setIcon(icon7)
        self.btnClearAll.setFlat(True)
        self.btnClearAll.setObjectName("btnClearAll")
        self.gridLayout_5.addWidget(self.btnClearAll, 2, 1, 1, 1)
        self.gridLayout_6.addWidget(self.frame_6, 0, 0, 1, 1)
        self.frame_12 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setMaximumSize(QtCore.QSize(16777215, 175))
        self.frame_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_12)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_16 = QtWidgets.QLabel(self.frame_12)
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_10.addWidget(self.label_16, 1, 4, 1, 1)
        self.txtDonorRegions = QtWidgets.QTextEdit(self.frame_12)
        self.txtDonorRegions.setMaximumSize(QtCore.QSize(16777215, 125))
        self.txtDonorRegions.setReadOnly(False)
        self.txtDonorRegions.setObjectName("txtDonorRegions")
        self.gridLayout_10.addWidget(self.txtDonorRegions, 2, 4, 1, 1)
        self.txtInsert_Base = QtWidgets.QTextEdit(self.frame_12)
        self.txtInsert_Base.setMinimumSize(QtCore.QSize(0, 0))
        self.txtInsert_Base.setMaximumSize(QtCore.QSize(16777215, 125))
        self.txtInsert_Base.setReadOnly(False)
        self.txtInsert_Base.setObjectName("txtInsert_Base")
        self.gridLayout_10.addWidget(self.txtInsert_Base, 2, 5, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.frame_12)
        self.label_63.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_63.setObjectName("label_63")
        self.gridLayout_10.addWidget(self.label_63, 1, 5, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.frame_12)
        self.frame_5.setMaximumSize(QtCore.QSize(200, 150))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout.setObjectName("gridLayout")
        self.cboForm = QtWidgets.QComboBox(self.frame_5)
        self.cboForm.setObjectName("cboForm")
        self.cboForm.addItem("")
        self.cboForm.addItem("")
        self.cboForm.addItem("")
        self.cboForm.addItem("")
        self.cboForm.addItem("")
        self.gridLayout.addWidget(self.cboForm, 3, 1, 1, 1)
        self.cboRole = QtWidgets.QComboBox(self.frame_5)
        self.cboRole.setObjectName("cboRole")
        self.cboRole.addItem("")
        self.cboRole.addItem("")
        self.cboRole.addItem("")
        self.cboRole.addItem("")
        self.gridLayout.addWidget(self.cboRole, 1, 1, 1, 1)
        self.lblRole = QtWidgets.QLabel(self.frame_5)
        self.lblRole.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lblRole.setObjectName("lblRole")
        self.gridLayout.addWidget(self.lblRole, 1, 0, 1, 1)
        self.label_64 = QtWidgets.QLabel(self.frame_5)
        self.label_64.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_64.setObjectName("label_64")
        self.gridLayout.addWidget(self.label_64, 3, 0, 1, 1)
        self.label_66 = QtWidgets.QLabel(self.frame_5)
        self.label_66.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_66.setObjectName("label_66")
        self.gridLayout.addWidget(self.label_66, 5, 0, 1, 1)
        self.cboSubtype = QtWidgets.QComboBox(self.frame_5)
        self.cboSubtype.setObjectName("cboSubtype")
        self.cboSubtype.addItem("")
        self.cboSubtype.addItem("")
        self.cboSubtype.addItem("")
        self.cboSubtype.addItem("")
        self.cboSubtype.addItem("")
        self.cboSubtype.addItem("")
        self.cboSubtype.addItem("")
        self.cboSubtype.addItem("")
        self.cboSubtype.addItem("")
        self.cboSubtype.addItem("")
        self.cboSubtype.addItem("")
        self.cboSubtype.addItem("")
        self.cboSubtype.addItem("")
        self.cboSubtype.addItem("")
        self.cboSubtype.addItem("")
        self.cboSubtype.addItem("")
        self.cboSubtype.addItem("")
        self.cboSubtype.addItem("")
        self.cboSubtype.addItem("")
        self.cboSubtype.addItem("")
        self.cboSubtype.addItem("")
        self.cboSubtype.addItem("")
        self.cboSubtype.addItem("")
        self.cboSubtype.addItem("")
        self.cboSubtype.addItem("")
        self.cboSubtype.addItem("")
        self.cboSubtype.addItem("")
        self.cboSubtype.addItem("")
        self.cboSubtype.addItem("")
        self.cboSubtype.addItem("")
        self.cboSubtype.addItem("")
        self.gridLayout.addWidget(self.cboSubtype, 5, 1, 1, 1)
        self.gridLayout_10.addWidget(self.frame_5, 2, 3, 1, 1)
        self.gridLayout_6.addWidget(self.frame_12, 2, 0, 1, 1)
        self.txtName = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents_2)
        self.txtName.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.txtName.setFont(font)
        self.txtName.setReadOnly(True)
        self.txtName.setObjectName("txtName")
        self.gridLayout_6.addWidget(self.txtName, 1, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout.addWidget(self.scrollArea_2)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/PNG-Icons/print.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabMain, icon8, "")
        self.tabSequence = QtWidgets.QWidget()
        self.tabSequence.setObjectName("tabSequence")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.tabSequence)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.lblAAseq = QtWidgets.QLabel(self.tabSequence)
        self.lblAAseq.setMinimumSize(QtCore.QSize(0, 0))
        self.lblAAseq.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setBold(True)
        font.setWeight(75)
        self.lblAAseq.setFont(font)
        self.lblAAseq.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblAAseq.setWordWrap(True)
        self.lblAAseq.setObjectName("lblAAseq")
        self.gridLayout_17.addWidget(self.lblAAseq, 6, 0, 1, 1)
        self.txtAASeq = QtWidgets.QTextEdit(self.tabSequence)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.txtAASeq.setFont(font)
        self.txtAASeq.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.txtAASeq.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.txtAASeq.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.txtAASeq.setAcceptRichText(True)
        self.txtAASeq.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.txtAASeq.setObjectName("txtAASeq")
        self.gridLayout_17.addWidget(self.txtAASeq, 8, 0, 1, 6)
        self.groupBox = QtWidgets.QGroupBox(self.tabSequence)
        self.groupBox.setMinimumSize(QtCore.QSize(945, 60))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnH3Num = QtWidgets.QPushButton(self.groupBox)
        self.btnH3Num.setMinimumSize(QtCore.QSize(0, 30))
        self.btnH3Num.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnH3Num.setAutoFillBackground(False)
        self.btnH3Num.setCheckable(True)
        self.btnH3Num.setChecked(True)
        self.btnH3Num.setFlat(True)
        self.btnH3Num.setObjectName("btnH3Num")
        self.horizontalLayout.addWidget(self.btnH3Num)
        self.btnH1Num = QtWidgets.QPushButton(self.groupBox)
        self.btnH1Num.setMinimumSize(QtCore.QSize(0, 30))
        self.btnH1Num.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnH1Num.setAutoFillBackground(False)
        self.btnH1Num.setCheckable(True)
        self.btnH1Num.setChecked(True)
        self.btnH1Num.setFlat(True)
        self.btnH1Num.setObjectName("btnH1Num")
        self.horizontalLayout.addWidget(self.btnH1Num)
        self.btnMuts = QtWidgets.QPushButton(self.groupBox)
        self.btnMuts.setMinimumSize(QtCore.QSize(0, 30))
        self.btnMuts.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnMuts.setAutoFillBackground(False)
        self.btnMuts.setCheckable(True)
        self.btnMuts.setChecked(True)
        self.btnMuts.setFlat(True)
        self.btnMuts.setObjectName("btnMuts")
        self.horizontalLayout.addWidget(self.btnMuts)
        self.btnDonReg = QtWidgets.QPushButton(self.groupBox)
        self.btnDonReg.setMinimumSize(QtCore.QSize(0, 30))
        self.btnDonReg.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnDonReg.setAutoFillBackground(False)
        self.btnDonReg.setCheckable(True)
        self.btnDonReg.setChecked(False)
        self.btnDonReg.setFlat(True)
        self.btnDonReg.setObjectName("btnDonReg")
        self.horizontalLayout.addWidget(self.btnDonReg)
        self.gridLayout_17.addWidget(self.groupBox, 5, 0, 1, 6)
        self.label_19 = QtWidgets.QLabel(self.tabSequence)
        self.label_19.setObjectName("label_19")
        self.gridLayout_17.addWidget(self.label_19, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.tabSequence)
        self.label.setObjectName("label")
        self.gridLayout_17.addWidget(self.label, 6, 1, 1, 2)
        self.cboSubtype_2 = QtWidgets.QComboBox(self.tabSequence)
        self.cboSubtype_2.setObjectName("cboSubtype_2")
        self.cboSubtype_2.addItem("")
        self.cboSubtype_2.addItem("")
        self.cboSubtype_2.addItem("")
        self.cboSubtype_2.addItem("")
        self.cboSubtype_2.addItem("")
        self.cboSubtype_2.addItem("")
        self.cboSubtype_2.addItem("")
        self.cboSubtype_2.addItem("")
        self.cboSubtype_2.addItem("")
        self.cboSubtype_2.addItem("")
        self.cboSubtype_2.addItem("")
        self.cboSubtype_2.addItem("")
        self.cboSubtype_2.addItem("")
        self.cboSubtype_2.addItem("")
        self.cboSubtype_2.addItem("")
        self.cboSubtype_2.addItem("")
        self.cboSubtype_2.addItem("")
        self.cboSubtype_2.addItem("")
        self.cboSubtype_2.addItem("")
        self.cboSubtype_2.addItem("")
        self.cboSubtype_2.addItem("")
        self.cboSubtype_2.addItem("")
        self.cboSubtype_2.addItem("")
        self.cboSubtype_2.addItem("")
        self.cboSubtype_2.addItem("")
        self.cboSubtype_2.addItem("")
        self.cboSubtype_2.addItem("")
        self.cboSubtype_2.addItem("")
        self.cboSubtype_2.addItem("")
        self.cboSubtype_2.addItem("")
        self.cboSubtype_2.addItem("")
        self.gridLayout_17.addWidget(self.cboSubtype_2, 1, 2, 1, 1)
        self.txtSeqName2 = QtWidgets.QPlainTextEdit(self.tabSequence)
        self.txtSeqName2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.txtSeqName2.setObjectName("txtSeqName2")
        self.gridLayout_17.addWidget(self.txtSeqName2, 0, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tabSequence)
        self.label_20.setObjectName("label_20")
        self.gridLayout_17.addWidget(self.label_20, 1, 0, 1, 1)
        self.lblSeq2 = QtWidgets.QLabel(self.tabSequence)
        self.lblSeq2.setText("")
        self.lblSeq2.setObjectName("lblSeq2")
        self.gridLayout_17.addWidget(self.lblSeq2, 6, 4, 1, 1)
        self.frame_18 = QtWidgets.QFrame(self.tabSequence)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_18.sizePolicy().hasHeightForWidth())
        self.frame_18.setSizePolicy(sizePolicy)
        self.frame_18.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.txtName_2 = QtWidgets.QTextEdit(self.frame_18)
        self.txtName_2.setGeometry(QtCore.QRect(77, 14, 851, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtName_2.sizePolicy().hasHeightForWidth())
        self.txtName_2.setSizePolicy(sizePolicy)
        self.txtName_2.setMinimumSize(QtCore.QSize(0, 25))
        self.txtName_2.setMaximumSize(QtCore.QSize(1000, 20))
        self.txtName_2.setObjectName("txtName_2")
        self.seqlabel_23 = QtWidgets.QLabel(self.frame_18)
        self.seqlabel_23.setGeometry(QtCore.QRect(12, 12, 44, 17))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seqlabel_23.sizePolicy().hasHeightForWidth())
        self.seqlabel_23.setSizePolicy(sizePolicy)
        self.seqlabel_23.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(14)
        self.seqlabel_23.setFont(font)
        self.seqlabel_23.setObjectName("seqlabel_23")
        self.seqlabel_21 = QtWidgets.QLabel(self.frame_18)
        self.seqlabel_21.setGeometry(QtCore.QRect(12, 47, 55, 17))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seqlabel_21.sizePolicy().hasHeightForWidth())
        self.seqlabel_21.setSizePolicy(sizePolicy)
        self.seqlabel_21.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(14)
        self.seqlabel_21.setFont(font)
        self.seqlabel_21.setObjectName("seqlabel_21")
        self.txtGroup_2 = QtWidgets.QTextEdit(self.frame_18)
        self.txtGroup_2.setGeometry(QtCore.QRect(77, 49, 244, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtGroup_2.sizePolicy().hasHeightForWidth())
        self.txtGroup_2.setSizePolicy(sizePolicy)
        self.txtGroup_2.setMinimumSize(QtCore.QSize(0, 25))
        self.txtGroup_2.setMaximumSize(QtCore.QSize(1000, 20))
        self.txtGroup_2.setObjectName("txtGroup_2")
        self.gridLayout_17.addWidget(self.frame_18, 4, 0, 1, 6)
        self.frame_18.raise_()
        self.groupBox.raise_()
        self.txtAASeq.raise_()
        self.lblSeq2.raise_()
        self.lblAAseq.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.cboSubtype_2.raise_()
        self.txtSeqName2.raise_()
        self.label.raise_()
        self.tabWidget.addTab(self.tabSequence, icon8, "")
        self.tabAlignment = QtWidgets.QWidget()
        self.tabAlignment.setObjectName("tabAlignment")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.tabAlignment)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.lblAlignment = QtWidgets.QLabel(self.tabAlignment)
        self.lblAlignment.setMinimumSize(QtCore.QSize(500, 0))
        self.lblAlignment.setObjectName("lblAlignment")
        self.gridLayout_16.addWidget(self.lblAlignment, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(532, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem1, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tabAlignment)
        self.label_8.setObjectName("label_8")
        self.gridLayout_16.addWidget(self.label_8, 0, 2, 1, 1)
        self.spnAlignFont = QtWidgets.QSpinBox(self.tabAlignment)
        self.spnAlignFont.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.spnAlignFont.setMinimum(6)
        self.spnAlignFont.setMaximum(36)
        self.spnAlignFont.setProperty("value", 13)
        self.spnAlignFont.setObjectName("spnAlignFont")
        self.gridLayout_16.addWidget(self.spnAlignFont, 0, 3, 1, 1)
        self.txtSeqAlignment = QtWidgets.QTextEdit(self.tabAlignment)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(13)
        self.txtSeqAlignment.setFont(font)
        self.txtSeqAlignment.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.txtSeqAlignment.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.txtSeqAlignment.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.txtSeqAlignment.setObjectName("txtSeqAlignment")
        self.gridLayout_16.addWidget(self.txtSeqAlignment, 1, 0, 1, 4)
        self.tabWidget.addTab(self.tabAlignment, icon8, "")
        self.tabAliHTML = QtWidgets.QWidget()
        self.tabAliHTML.setObjectName("tabAliHTML")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tabAliHTML)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.MSAgroupBox = QtWidgets.QGroupBox(self.tabAliHTML)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.MSAgroupBox.setFont(font)
        self.MSAgroupBox.setObjectName("MSAgroupBox")
        self.gridLayout_7.addWidget(self.MSAgroupBox, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabAliHTML, "")
        self.tabSeqDB = QtWidgets.QWidget()
        self.tabSeqDB.setObjectName("tabSeqDB")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.tabSeqDB)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.label_3 = QtWidgets.QLabel(self.tabSeqDB)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_21.addWidget(self.label_3, 0, 0, 1, 1)
        self.EditLock = QtWidgets.QPushButton(self.tabSeqDB)
        self.EditLock.setMaximumSize(QtCore.QSize(100, 16777215))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/PNG-Icons/locked.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.EditLock.setIcon(icon9)
        self.EditLock.setIconSize(QtCore.QSize(30, 30))
        self.EditLock.setFlat(True)
        self.EditLock.setObjectName("EditLock")
        self.gridLayout_21.addWidget(self.EditLock, 0, 1, 1, 1)
        self.SeqTable = QtWidgets.QTableWidget(self.tabSeqDB)
        self.SeqTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.SeqTable.setObjectName("SeqTable")
        self.SeqTable.setColumnCount(0)
        self.SeqTable.setRowCount(0)
        self.gridLayout_21.addWidget(self.SeqTable, 3, 0, 1, 2)
        self.tabWidget.addTab(self.tabSeqDB, "")
        self.tabSummary = QtWidgets.QWidget()
        self.tabSummary.setObjectName("tabSummary")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tabSummary)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox1 = QtWidgets.QGroupBox(self.tabSummary)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.groupBox1.setFont(font)
        self.groupBox1.setObjectName("groupBox1")
        self.gridLayout_3.addWidget(self.groupBox1, 0, 0, 1, 1)
        self.groupBox2 = QtWidgets.QGroupBox(self.tabSummary)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.groupBox2.setFont(font)
        self.groupBox2.setObjectName("groupBox2")
        self.gridLayout_3.addWidget(self.groupBox2, 0, 1, 1, 1)
        self.groupBox3 = QtWidgets.QGroupBox(self.tabSummary)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.groupBox3.setFont(font)
        self.groupBox3.setObjectName("groupBox3")
        self.gridLayout_3.addWidget(self.groupBox3, 1, 0, 1, 2)
        self.tabWidget.addTab(self.tabSummary, "")
        self.tabHTML = QtWidgets.QWidget()
        self.tabHTML.setObjectName("tabHTML")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tabHTML)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBoxHTML1 = QtWidgets.QGroupBox(self.tabHTML)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.groupBoxHTML1.setFont(font)
        self.groupBoxHTML1.setObjectName("groupBoxHTML1")
        self.gridLayout_4.addWidget(self.groupBoxHTML1, 0, 0, 1, 1)
        self.groupBoxHTML2 = QtWidgets.QGroupBox(self.tabHTML)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.groupBoxHTML2.setFont(font)
        self.groupBoxHTML2.setObjectName("groupBoxHTML2")
        self.gridLayout_4.addWidget(self.groupBoxHTML2, 0, 1, 1, 1)
        self.groupBoxHTML3 = QtWidgets.QGroupBox(self.tabHTML)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.groupBoxHTML3.setFont(font)
        self.groupBoxHTML3.setObjectName("groupBoxHTML3")
        self.gridLayout_4.addWidget(self.groupBoxHTML3, 1, 0, 1, 2)
        self.tabWidget.addTab(self.tabHTML, "")
        self.tabFragment = QtWidgets.QWidget()
        self.tabFragment.setObjectName("tabFragment")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.tabFragment)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tabFragment)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 200))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.FragmentTab = QtWidgets.QTabWidget(self.groupBox_2)
        self.FragmentTab.setMaximumSize(QtCore.QSize(16777215, 120))
        self.FragmentTab.setObjectName("FragmentTab")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.browseFragmentDB = QtWidgets.QPushButton(self.tab_4)
        self.browseFragmentDB.setObjectName("browseFragmentDB")
        self.gridLayout_12.addWidget(self.browseFragmentDB, 0, 1, 1, 1)
        self.dbpath = QtWidgets.QLineEdit(self.tab_4)
        self.dbpath.setObjectName("dbpath")
        self.gridLayout_12.addWidget(self.dbpath, 0, 0, 1, 1)
        self.FragmentTab.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_9 = QtWidgets.QLabel(self.tab_5)
        self.label_9.setObjectName("label_9")
        self.gridLayout_15.addWidget(self.label_9, 0, 5, 1, 1)
        self.DBnameinput = QtWidgets.QLineEdit(self.tab_5)
        self.DBnameinput.setObjectName("DBnameinput")
        self.gridLayout_15.addWidget(self.DBnameinput, 0, 6, 1, 1)
        self.Userinput = QtWidgets.QLineEdit(self.tab_5)
        self.Userinput.setObjectName("Userinput")
        self.gridLayout_15.addWidget(self.Userinput, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_5)
        self.label_11.setObjectName("label_11")
        self.gridLayout_15.addWidget(self.label_11, 1, 0, 1, 1)
        self.Portinput = QtWidgets.QLineEdit(self.tab_5)
        self.Portinput.setObjectName("Portinput")
        self.gridLayout_15.addWidget(self.Portinput, 0, 3, 1, 2)
        self.label_12 = QtWidgets.QLabel(self.tab_5)
        self.label_12.setObjectName("label_12")
        self.gridLayout_15.addWidget(self.label_12, 1, 2, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.tab_5)
        self.label_7.setObjectName("label_7")
        self.gridLayout_15.addWidget(self.label_7, 0, 0, 1, 1)
        self.Passinput = QtWidgets.QLineEdit(self.tab_5)
        self.Passinput.setObjectName("Passinput")
        self.gridLayout_15.addWidget(self.Passinput, 1, 4, 1, 3)
        self.label_13 = QtWidgets.QLabel(self.tab_5)
        self.label_13.setObjectName("label_13")
        self.gridLayout_15.addWidget(self.label_13, 0, 2, 1, 1)
        self.IPinput = QtWidgets.QLineEdit(self.tab_5)
        self.IPinput.setObjectName("IPinput")
        self.gridLayout_15.addWidget(self.IPinput, 0, 1, 1, 1)
        self.FragmentTab.addTab(self.tab_5, "")
        self.gridLayout_18.addWidget(self.FragmentTab, 0, 0, 1, 1)
        self.connectFragmentDB = QtWidgets.QPushButton(self.groupBox_2)
        self.connectFragmentDB.setMaximumSize(QtCore.QSize(200, 32))
        self.connectFragmentDB.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.connectFragmentDB.setObjectName("connectFragmentDB")
        self.gridLayout_18.addWidget(self.connectFragmentDB, 1, 0, 1, 1)
        self.gridLayout_22.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tabFragment)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_6)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(50)
        self.gridLayout_23.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.gridLayout_22.addWidget(self.groupBox_6, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tabFragment, "")
        self.gridLayout_2.addWidget(self.tabWidget, 1, 0, 1, 1)
        MainLibrator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainLibrator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1104, 22))
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSequences = QtWidgets.QMenu(self.menubar)
        self.menuSequences.setObjectName("menuSequences")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuSetting = QtWidgets.QMenu(self.menubar)
        self.menuSetting.setObjectName("menuSetting")
        self.menuEdit_Sequence = QtWidgets.QMenu(self.menubar)
        self.menuEdit_Sequence.setObjectName("menuEdit_Sequence")
        self.menuVisualization = QtWidgets.QMenu(self.menubar)
        self.menuVisualization.setObjectName("menuVisualization")
        self.menuGibsonClone = QtWidgets.QMenu(self.menubar)
        self.menuGibsonClone.setObjectName("menuGibsonClone")
        MainLibrator.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainLibrator)
        self.statusbar.setObjectName("statusbar")
        MainLibrator.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainLibrator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        self.toolBar.setMovable(False)
        self.toolBar.setIconSize(QtCore.QSize(24, 24))
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        MainLibrator.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_Open = QtWidgets.QAction(MainLibrator)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/PNG-Icons/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Open.setIcon(icon10)
        self.action_Open.setObjectName("action_Open")
        self.action_New = QtWidgets.QAction(MainLibrator)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/PNG-Icons/page.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon11.addPixmap(QtGui.QPixmap("../../../../Applications/Python 3.4/PyQt-gpl-5.3.1/examples/mainwindows/mdi/images/new.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.action_New.setIcon(icon11)
        self.action_New.setObjectName("action_New")
        self.action_Import = QtWidgets.QAction(MainLibrator)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/PNG-Icons/Import.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Import.setIcon(icon12)
        self.action_Import.setObjectName("action_Import")
        self.actionExport = QtWidgets.QAction(MainLibrator)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/PNG-Icons/Export.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExport.setIcon(icon13)
        self.actionExport.setObjectName("actionExport")
        self.actionIMGT = QtWidgets.QAction(MainLibrator)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/PNG-Icons/IMGT.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionIMGT.setIcon(icon14)
        self.actionIMGT.setObjectName("actionIMGT")
        self.actionIgBlast = QtWidgets.QAction(MainLibrator)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/PNG-Icons/NCBI.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionIgBlast.setIcon(icon15)
        self.actionIgBlast.setObjectName("actionIgBlast")
        self.actionHANumbering = QtWidgets.QAction(MainLibrator)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/PNG-Icons/SHM.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHANumbering.setIcon(icon16)
        self.actionHANumbering.setObjectName("actionHANumbering")
        self.actionMultiple_Alignement = QtWidgets.QAction(MainLibrator)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/PNG-Icons/Muli.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMultiple_Alignement.setIcon(icon17)
        self.actionMultiple_Alignement.setObjectName("actionMultiple_Alignement")
        self.actionImportLei = QtWidgets.QAction(MainLibrator)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/PNG-Icons/Align.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionImportLei.setIcon(icon18)
        self.actionImportLei.setObjectName("actionImportLei")
        self.actionPreferences = QtWidgets.QAction(MainLibrator)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/PNG-Icons/process.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPreferences.setIcon(icon19)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionPrint = QtWidgets.QAction(MainLibrator)
        self.actionPrint.setIcon(icon8)
        self.actionPrint.setObjectName("actionPrint")
        self.actionPaste_from_Clipboard = QtWidgets.QAction(MainLibrator)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/PNG-Icons/Paste.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPaste_from_Clipboard.setIcon(icon20)
        self.actionPaste_from_Clipboard.setObjectName("actionPaste_from_Clipboard")
        self.actionCopy = QtWidgets.QAction(MainLibrator)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/PNG-Icons/pages.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopy.setIcon(icon21)
        self.actionCopy.setObjectName("actionCopy")
        self.actionCut = QtWidgets.QAction(MainLibrator)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/PNG-Icons/scissor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCut.setIcon(icon22)
        self.actionCut.setObjectName("actionCut")
        self.actionPaste = QtWidgets.QAction(MainLibrator)
        self.actionPaste.setIcon(icon20)
        self.actionPaste.setObjectName("actionPaste")
        self.action_Save = QtWidgets.QAction(MainLibrator)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/PNG-Icons/SaveIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Save.setIcon(icon23)
        self.action_Save.setObjectName("action_Save")
        self.actionAbout_2 = QtWidgets.QAction(MainLibrator)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/PNG-Icons/warning.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout_2.setIcon(icon24)
        self.actionAbout_2.setObjectName("actionAbout_2")
        self.action_Help = QtWidgets.QAction(MainLibrator)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/PNG-Icons/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Help.setIcon(icon25)
        self.action_Help.setObjectName("action_Help")
        self.actionTop = QtWidgets.QAction(MainLibrator)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(":/PNG-Icons/left_arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTop.setIcon(icon26)
        self.actionTop.setObjectName("actionTop")
        self.actionBottom = QtWidgets.QAction(MainLibrator)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(":/PNG-Icons/right_arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBottom.setIcon(icon27)
        self.actionBottom.setObjectName("actionBottom")
        self.actionMove_Up = QtWidgets.QAction(MainLibrator)
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(":/PNG-Icons/up_arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMove_Up.setIcon(icon28)
        self.actionMove_Up.setObjectName("actionMove_Up")
        self.actionMove_Down = QtWidgets.QAction(MainLibrator)
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(":/PNG-Icons/down_arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMove_Down.setIcon(icon29)
        self.actionMove_Down.setObjectName("actionMove_Down")
        self.actionFind_Clonal = QtWidgets.QAction(MainLibrator)
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(":/PNG-Icons/Clonal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFind_Clonal.setIcon(icon30)
        self.actionFind_Clonal.setObjectName("actionFind_Clonal")
        self.actionSave_As = QtWidgets.QAction(MainLibrator)
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap(":/PNG-Icons/SaveAsIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_As.setIcon(icon31)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionDelete_record = QtWidgets.QAction(MainLibrator)
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap(":/PNG-Icons/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDelete_record.setIcon(icon32)
        self.actionDelete_record.setObjectName("actionDelete_record")
        self.actionAdd_record = QtWidgets.QAction(MainLibrator)
        self.actionAdd_record.setObjectName("actionAdd_record")
        self.actionDuplicate_current = QtWidgets.QAction(MainLibrator)
        self.actionDuplicate_current.setObjectName("actionDuplicate_current")
        self.actionView_subset = QtWidgets.QAction(MainLibrator)
        self.actionView_subset.setObjectName("actionView_subset")
        self.actionReport = QtWidgets.QAction(MainLibrator)
        self.actionReport.setObjectName("actionReport")
        self.actionGenerate_from_file = QtWidgets.QAction(MainLibrator)
        self.actionGenerate_from_file.setObjectName("actionGenerate_from_file")
        self.actionIncrease_font_size = QtWidgets.QAction(MainLibrator)
        self.actionIncrease_font_size.setIcon(icon6)
        self.actionIncrease_font_size.setObjectName("actionIncrease_font_size")
        self.actionDecrease_font_size = QtWidgets.QAction(MainLibrator)
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap(":/PNG-Icons/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDecrease_font_size.setIcon(icon33)
        self.actionDecrease_font_size.setObjectName("actionDecrease_font_size")
        self.actionAlignment_4 = QtWidgets.QAction(MainLibrator)
        self.actionAlignment_4.setObjectName("actionAlignment_4")
        self.actionCreateVDJdb = QtWidgets.QAction(MainLibrator)
        icon34 = QtGui.QIcon()
        icon34.addPixmap(QtGui.QPixmap(":/PNG-Icons/address_book.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCreateVDJdb.setIcon(icon34)
        self.actionCreateVDJdb.setObjectName("actionCreateVDJdb")
        self.actionDNA = QtWidgets.QAction(MainLibrator)
        self.actionDNA.setCheckable(True)
        self.actionDNA.setChecked(True)
        self.actionDNA.setObjectName("actionDNA")
        self.actionAA = QtWidgets.QAction(MainLibrator)
        self.actionAA.setCheckable(True)
        self.actionAA.setObjectName("actionAA")
        self.actionBA = QtWidgets.QAction(MainLibrator)
        self.actionBA.setCheckable(True)
        self.actionBA.setObjectName("actionBA")
        self.actionIsotypes = QtWidgets.QAction(MainLibrator)
        self.actionIsotypes.setObjectName("actionIsotypes")
        self.actionMap_hotspots = QtWidgets.QAction(MainLibrator)
        self.actionMap_hotspots.setObjectName("actionMap_hotspots")
        self.actionImport_Vgenes_database = QtWidgets.QAction(MainLibrator)
        self.actionImport_Vgenes_database.setObjectName("actionImport_Vgenes_database")
        self.actionCreateAnalysisDB = QtWidgets.QAction(MainLibrator)
        self.actionCreateAnalysisDB.setObjectName("actionCreateAnalysisDB")
        self.actionTree = QtWidgets.QAction(MainLibrator)
        icon35 = QtGui.QIcon()
        icon35.addPixmap(QtGui.QPixmap(":/PNG-Icons/treeAA.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTree.setIcon(icon35)
        self.actionTree.setObjectName("actionTree")
        self.actionRevert_to_previous = QtWidgets.QAction(MainLibrator)
        icon36 = QtGui.QIcon()
        icon36.addPixmap(QtGui.QPixmap(":/PNG-Icons/rewind.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRevert_to_previous.setIcon(icon36)
        self.actionRevert_to_previous.setObjectName("actionRevert_to_previous")
        self.actionAnalyze_Isotypes = QtWidgets.QAction(MainLibrator)
        icon37 = QtGui.QIcon()
        icon37.addPixmap(QtGui.QPixmap(":/PNG-Icons/yen_currency_sign.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAnalyze_Isotypes.setIcon(icon37)
        self.actionAnalyze_Isotypes.setObjectName("actionAnalyze_Isotypes")
        self.actionMerge_fastq_Ends = QtWidgets.QAction(MainLibrator)
        self.actionMerge_fastq_Ends.setObjectName("actionMerge_fastq_Ends")
        self.actionMergeMySeq = QtWidgets.QAction(MainLibrator)
        self.actionMergeMySeq.setObjectName("actionMergeMySeq")
        self.actionImportCluster = QtWidgets.QAction(MainLibrator)
        self.actionImportCluster.setObjectName("actionImportCluster")
        self.actionRename10x = QtWidgets.QAction(MainLibrator)
        self.actionRename10x.setObjectName("actionRename10x")
        self.actionFixNames = QtWidgets.QAction(MainLibrator)
        self.actionFixNames.setObjectName("actionFixNames")
        self.actionOpen_last = QtWidgets.QAction(MainLibrator)
        self.actionOpen_last.setObjectName("actionOpen_last")
        self.actionClean = QtWidgets.QAction(MainLibrator)
        self.actionClean.setIcon(icon5)
        self.actionClean.setObjectName("actionClean")
        self.actionNTTree = QtWidgets.QAction(MainLibrator)
        icon38 = QtGui.QIcon()
        icon38.addPixmap(QtGui.QPixmap(":/PNG-Icons/treeNT.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNTTree.setIcon(icon38)
        self.actionNTTree.setObjectName("actionNTTree")
        self.actionCheck_Update_base_folder = QtWidgets.QAction(MainLibrator)
        self.actionCheck_Update_base_folder.setObjectName("actionCheck_Update_base_folder")
        self.actionMutation = QtWidgets.QAction(MainLibrator)
        icon39 = QtGui.QIcon()
        icon39.addPixmap(QtGui.QPixmap(":/PNG-Icons/Mutation.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMutation.setIcon(icon39)
        self.actionMutation.setObjectName("actionMutation")
        self.actionEditing = QtWidgets.QAction(MainLibrator)
        icon40 = QtGui.QIcon()
        icon40.addPixmap(QtGui.QPixmap(":/PNG-Icons/EditSeq.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEditing.setIcon(icon40)
        self.actionEditing.setObjectName("actionEditing")
        self.actionFusion = QtWidgets.QAction(MainLibrator)
        icon41 = QtGui.QIcon()
        icon41.addPixmap(QtGui.QPixmap(":/PNG-Icons/Fusion.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFusion.setIcon(icon41)
        self.actionFusion.setObjectName("actionFusion")
        self.actionPyMOL = QtWidgets.QAction(MainLibrator)
        self.actionPyMOL.setIcon(icon1)
        self.actionPyMOL.setObjectName("actionPyMOL")
        self.actionGibsonClone = QtWidgets.QAction(MainLibrator)
        self.actionGibsonClone.setIcon(icon)
        self.actionGibsonClone.setObjectName("actionGibsonClone")
        self.actionGibsonClone_Setting = QtWidgets.QAction(MainLibrator)
        icon42 = QtGui.QIcon()
        icon42.addPixmap(QtGui.QPixmap(":/PNG-Icons/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGibsonClone_Setting.setIcon(icon42)
        self.actionGibsonClone_Setting.setObjectName("actionGibsonClone_Setting")
        self.actionAlignmentHTML = QtWidgets.QAction(MainLibrator)
        self.actionAlignmentHTML.setEnabled(True)
        icon43 = QtGui.QIcon()
        icon43.addPixmap(QtGui.QPixmap(":/PNG-Icons/MSA.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAlignmentHTML.setIcon(icon43)
        self.actionAlignmentHTML.setAutoRepeat(True)
        self.actionAlignmentHTML.setObjectName("actionAlignmentHTML")
        self.actionVector_Joint_Setting = QtWidgets.QAction(MainLibrator)
        self.actionVector_Joint_Setting.setObjectName("actionVector_Joint_Setting")
        self.actionFusion_High_resolution = QtWidgets.QAction(MainLibrator)
        self.actionFusion_High_resolution.setObjectName("actionFusion_High_resolution")
        self.actionFusion_Low_reslution = QtWidgets.QAction(MainLibrator)
        self.actionFusion_Low_reslution.setObjectName("actionFusion_Low_reslution")
        self.menuFile.addAction(self.action_New)
        self.menuFile.addAction(self.action_Open)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrint)
        self.menuSequences.addAction(self.action_Import)
        self.menuSequences.addAction(self.actionExport)
        self.menuTools.addAction(self.actionHANumbering)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionAlignmentHTML)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionNTTree)
        self.menuTools.addAction(self.actionTree)
        self.menuHelp.addAction(self.action_Help)
        self.menuView.addAction(self.actionAlignment_4)
        self.menuView.addAction(self.actionIncrease_font_size)
        self.menuView.addAction(self.actionDecrease_font_size)
        self.menuSetting.addAction(self.actionPreferences)
        self.menuEdit_Sequence.addAction(self.actionMutation)
        self.menuEdit_Sequence.addSeparator()
        self.menuEdit_Sequence.addAction(self.actionEditing)
        self.menuEdit_Sequence.addSeparator()
        self.menuEdit_Sequence.addAction(self.actionFusion)
        self.menuEdit_Sequence.addAction(self.actionFusion_High_resolution)
        self.menuEdit_Sequence.addAction(self.actionFusion_Low_reslution)
        self.menuVisualization.addAction(self.actionPyMOL)
        self.menuGibsonClone.addAction(self.actionGibsonClone)
        self.menuGibsonClone.addAction(self.actionGibsonClone_Setting)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSequences.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuEdit_Sequence.menuAction())
        self.menubar.addAction(self.menuVisualization.menuAction())
        self.menubar.addAction(self.menuGibsonClone.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_New)
        self.toolBar.addAction(self.action_Open)
        self.toolBar.addAction(self.actionPrint)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Import)
        self.toolBar.addAction(self.actionExport)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionHANumbering)
        self.toolBar.addAction(self.actionMutation)
        self.toolBar.addAction(self.actionEditing)
        self.toolBar.addAction(self.actionFusion)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionNTTree)
        self.toolBar.addAction(self.actionTree)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionAlignmentHTML)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionIncrease_font_size)
        self.toolBar.addAction(self.actionDecrease_font_size)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPreferences)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionClean)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Help)

        self.retranslateUi(MainLibrator)
        self.tabWidget.setCurrentIndex(0)
        self.FragmentTab.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainLibrator)

    def retranslateUi(self, MainLibrator):
        _translate = QtCore.QCoreApplication.translate
        MainLibrator.setWindowTitle(_translate("MainLibrator", "Librator"))
        self.label_4.setText(_translate("MainLibrator", "Base Sequence:"))
        self.gibsonBTN.setText(_translate("MainLibrator", "Gibson Clones"))
        self.pymolBTN.setText(_translate("MainLibrator", "3D Visualization"))
        self.tabWidget.setToolTip(_translate("MainLibrator", "<html><head/><body><p>Sequence</p></body></html>"))
        self.label_2.setText(_translate("MainLibrator", "Recent files:"))
        self.cboRecent.setItemText(0, _translate("MainLibrator", "Open previous"))
        self.btnCopyRecords.setToolTip(_translate("MainLibrator", "<html><head/><body><p>Copy checked records into another database</p></body></html>"))
        self.btnExtractRecords.setToolTip(_translate("MainLibrator", "<html><head/><body><p>Make a new VGenes database file from checked records</p></body></html>"))
        self.seqlabel_26.setText(_translate("MainLibrator", "Generate Sequences:"))
        self.cboReportOptions.setItemText(0, _translate("MainLibrator", "Select report type:"))
        self.cboReportOptions.setItemText(1, _translate("MainLibrator", "Mutate Sequences"))
        self.cboReportOptions.setItemText(2, _translate("MainLibrator", "Sequence Editing"))
        self.cboReportOptions.setItemText(3, _translate("MainLibrator", "Fusion Sequences"))
        self.cboReportOptions.setItemText(4, _translate("MainLibrator", "Make Secreted Probe"))
        self.lblDNA.setText(_translate("MainLibrator", "DNA Sequence:"))
        self.seqlabel_9.setText(_translate("MainLibrator", "From:"))
        self.btnReadingFrames.setText(_translate("MainLibrator", "Show Reading Frames"))
        self.seqlabel_10.setText(_translate("MainLibrator", "Coding Region:"))
        self.seqlabel_19.setText(_translate("MainLibrator", "To:"))
        self.SearchButton.setText(_translate("MainLibrator", "Search"))
        self.rdoAA.setText(_translate("MainLibrator", "Amino Acid"))
        self.rdoDNA.setText(_translate("MainLibrator", "DNA"))
        self.btnEditSequence.setText(_translate("MainLibrator", "Edit Sequence"))
        self.lblAA.setText(_translate("MainLibrator", "Amino Acid Sequence:"))
        self.label_28.setText(_translate("MainLibrator", "Available sequences:"))
        self.label_5.setText(_translate("MainLibrator", "Group by: "))
        self.groupCombo.setItemText(0, _translate("MainLibrator", "SubType"))
        self.groupCombo.setItemText(1, _translate("MainLibrator", "Role"))
        self.groupCombo.setItemText(2, _translate("MainLibrator", "Form"))
        self.label_29.setText(_translate("MainLibrator", "Active sequences:"))
        self.btnDelete.setText(_translate("MainLibrator", "Delete Records"))
        self.listWidgetStrainsIn.setSortingEnabled(True)
        self.btnImport.setText(_translate("MainLibrator", "Import Sequences"))
        self.btnClearAll.setText(_translate("MainLibrator", "Reset active sequence data"))
        self.label_16.setText(_translate("MainLibrator", "Donor regions:"))
        self.label_63.setText(_translate("MainLibrator", "Mutations:"))
        self.cboForm.setItemText(0, _translate("MainLibrator", "Full HA"))
        self.cboForm.setItemText(1, _translate("MainLibrator", "Probe HA"))
        self.cboForm.setItemText(2, _translate("MainLibrator", "Full NA"))
        self.cboForm.setItemText(3, _translate("MainLibrator", "Probe NA"))
        self.cboForm.setItemText(4, _translate("MainLibrator", "Other"))
        self.cboRole.setItemText(0, _translate("MainLibrator", "Unassigned"))
        self.cboRole.setItemText(1, _translate("MainLibrator", "BaseSeq"))
        self.cboRole.setItemText(2, _translate("MainLibrator", "Reference"))
        self.cboRole.setItemText(3, _translate("MainLibrator", "Generated"))
        self.lblRole.setText(_translate("MainLibrator", "Role:"))
        self.label_64.setText(_translate("MainLibrator", "Form:"))
        self.label_66.setText(_translate("MainLibrator", "Subtype:"))
        self.cboSubtype.setCurrentText(_translate("MainLibrator", "H1"))
        self.cboSubtype.setItemText(0, _translate("MainLibrator", "H1"))
        self.cboSubtype.setItemText(1, _translate("MainLibrator", "H2"))
        self.cboSubtype.setItemText(2, _translate("MainLibrator", "H3"))
        self.cboSubtype.setItemText(3, _translate("MainLibrator", "H4"))
        self.cboSubtype.setItemText(4, _translate("MainLibrator", "H5"))
        self.cboSubtype.setItemText(5, _translate("MainLibrator", "H6"))
        self.cboSubtype.setItemText(6, _translate("MainLibrator", "H7"))
        self.cboSubtype.setItemText(7, _translate("MainLibrator", "H8"))
        self.cboSubtype.setItemText(8, _translate("MainLibrator", "H9"))
        self.cboSubtype.setItemText(9, _translate("MainLibrator", "H10"))
        self.cboSubtype.setItemText(10, _translate("MainLibrator", "H11"))
        self.cboSubtype.setItemText(11, _translate("MainLibrator", "H12"))
        self.cboSubtype.setItemText(12, _translate("MainLibrator", "H13"))
        self.cboSubtype.setItemText(13, _translate("MainLibrator", "H14"))
        self.cboSubtype.setItemText(14, _translate("MainLibrator", "H15"))
        self.cboSubtype.setItemText(15, _translate("MainLibrator", "H16"))
        self.cboSubtype.setItemText(16, _translate("MainLibrator", "H17"))
        self.cboSubtype.setItemText(17, _translate("MainLibrator", "H18"))
        self.cboSubtype.setItemText(18, _translate("MainLibrator", "N1"))
        self.cboSubtype.setItemText(19, _translate("MainLibrator", "N2"))
        self.cboSubtype.setItemText(20, _translate("MainLibrator", "N3"))
        self.cboSubtype.setItemText(21, _translate("MainLibrator", "N4"))
        self.cboSubtype.setItemText(22, _translate("MainLibrator", "N5"))
        self.cboSubtype.setItemText(23, _translate("MainLibrator", "N6"))
        self.cboSubtype.setItemText(24, _translate("MainLibrator", "N7"))
        self.cboSubtype.setItemText(25, _translate("MainLibrator", "N8"))
        self.cboSubtype.setItemText(26, _translate("MainLibrator", "N9"))
        self.cboSubtype.setItemText(27, _translate("MainLibrator", "N10"))
        self.cboSubtype.setItemText(28, _translate("MainLibrator", "N11"))
        self.cboSubtype.setItemText(29, _translate("MainLibrator", "B"))
        self.cboSubtype.setItemText(30, _translate("MainLibrator", "Other"))
        self.txtName.setToolTip(_translate("MainLibrator", "Double click name to edit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMain), _translate("MainLibrator", "Main"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tabMain), _translate("MainLibrator", "Main page, this page is printable"))
        self.lblAAseq.setText(_translate("MainLibrator", "Sequence Map:"))
        self.groupBox.setTitle(_translate("MainLibrator", "Click feature to show for sequence:"))
        self.btnH3Num.setText(_translate("MainLibrator", "H3 Numbering"))
        self.btnH1Num.setText(_translate("MainLibrator", "H1 Numbering"))
        self.btnMuts.setText(_translate("MainLibrator", "Mutations"))
        self.btnDonReg.setText(_translate("MainLibrator", "Donor Regions"))
        self.label_19.setText(_translate("MainLibrator", "Sequence Name:"))
        self.label.setText(_translate("MainLibrator", "Please scroll to refresh the alignment if the content doesn\'t change"))
        self.cboSubtype_2.setCurrentText(_translate("MainLibrator", "H1"))
        self.cboSubtype_2.setItemText(0, _translate("MainLibrator", "H1"))
        self.cboSubtype_2.setItemText(1, _translate("MainLibrator", "H2"))
        self.cboSubtype_2.setItemText(2, _translate("MainLibrator", "H3"))
        self.cboSubtype_2.setItemText(3, _translate("MainLibrator", "H4"))
        self.cboSubtype_2.setItemText(4, _translate("MainLibrator", "H5"))
        self.cboSubtype_2.setItemText(5, _translate("MainLibrator", "H6"))
        self.cboSubtype_2.setItemText(6, _translate("MainLibrator", "H7"))
        self.cboSubtype_2.setItemText(7, _translate("MainLibrator", "H8"))
        self.cboSubtype_2.setItemText(8, _translate("MainLibrator", "H9"))
        self.cboSubtype_2.setItemText(9, _translate("MainLibrator", "H10"))
        self.cboSubtype_2.setItemText(10, _translate("MainLibrator", "H11"))
        self.cboSubtype_2.setItemText(11, _translate("MainLibrator", "H12"))
        self.cboSubtype_2.setItemText(12, _translate("MainLibrator", "H13"))
        self.cboSubtype_2.setItemText(13, _translate("MainLibrator", "H14"))
        self.cboSubtype_2.setItemText(14, _translate("MainLibrator", "H15"))
        self.cboSubtype_2.setItemText(15, _translate("MainLibrator", "H16"))
        self.cboSubtype_2.setItemText(16, _translate("MainLibrator", "H17"))
        self.cboSubtype_2.setItemText(17, _translate("MainLibrator", "H18"))
        self.cboSubtype_2.setItemText(18, _translate("MainLibrator", "N1"))
        self.cboSubtype_2.setItemText(19, _translate("MainLibrator", "N2"))
        self.cboSubtype_2.setItemText(20, _translate("MainLibrator", "N3"))
        self.cboSubtype_2.setItemText(21, _translate("MainLibrator", "N4"))
        self.cboSubtype_2.setItemText(22, _translate("MainLibrator", "N5"))
        self.cboSubtype_2.setItemText(23, _translate("MainLibrator", "N6"))
        self.cboSubtype_2.setItemText(24, _translate("MainLibrator", "N7"))
        self.cboSubtype_2.setItemText(25, _translate("MainLibrator", "N8"))
        self.cboSubtype_2.setItemText(26, _translate("MainLibrator", "N9"))
        self.cboSubtype_2.setItemText(27, _translate("MainLibrator", "N10"))
        self.cboSubtype_2.setItemText(28, _translate("MainLibrator", "N11"))
        self.cboSubtype_2.setItemText(29, _translate("MainLibrator", "B"))
        self.cboSubtype_2.setItemText(30, _translate("MainLibrator", "Other"))
        self.label_20.setText(_translate("MainLibrator", "Subtype:"))
        self.seqlabel_23.setText(_translate("MainLibrator", "Name:"))
        self.seqlabel_21.setText(_translate("MainLibrator", "Subtype"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSequence), _translate("MainLibrator", "Sequence"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tabSequence), _translate("MainLibrator", "Sequence page, this page is printable"))
        self.lblAlignment.setText(_translate("MainLibrator", "Muscle Alignment:"))
        self.label_8.setText(_translate("MainLibrator", "Font Size (Ctrl+, Ctrl-): "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAlignment), _translate("MainLibrator", "Alignment(RTF)"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tabAlignment), _translate("MainLibrator", "Alignement (RTF) page, this page is printable"))
        self.MSAgroupBox.setTitle(_translate("MainLibrator", "Multiple Sequence Alignment"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAliHTML), _translate("MainLibrator", "Alignment(HTML)"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tabAliHTML), _translate("MainLibrator", "Alignement (HTML) page"))
        self.label_3.setText(_translate("MainLibrator", "Current Sequence Database"))
        self.EditLock.setText(_translate("MainLibrator", "Edit Lock"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSeqDB), _translate("MainLibrator", "SequenceDB"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tabSeqDB), _translate("MainLibrator", "Sequence Database page"))
        self.groupBox1.setTitle(_translate("MainLibrator", "Subtype in current DB"))
        self.groupBox2.setTitle(_translate("MainLibrator", "Role in current DB"))
        self.groupBox3.setTitle(_translate("MainLibrator", "Amino Acid Variation of Influenza HA/NA"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSummary), _translate("MainLibrator", "Summary"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tabSummary), _translate("MainLibrator", "Summary of current Sequence Database"))
        self.groupBoxHTML1.setTitle(_translate("MainLibrator", "Subtype in current DB"))
        self.groupBoxHTML2.setTitle(_translate("MainLibrator", "Role in current DB"))
        self.groupBoxHTML3.setTitle(_translate("MainLibrator", "Amino Acid Variation of Influenza HA/NA"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabHTML), _translate("MainLibrator", "Summary(HTML)"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tabHTML), _translate("MainLibrator", "Summary (HTML) of current Sequence Database "))
        self.groupBox_2.setTitle(_translate("MainLibrator", "Setup Database information"))
        self.browseFragmentDB.setText(_translate("MainLibrator", "Browse"))
        self.FragmentTab.setTabText(self.FragmentTab.indexOf(self.tab_4), _translate("MainLibrator", "Loacl DB (SQLite)"))
        self.label_9.setText(_translate("MainLibrator", "DB name"))
        self.label_11.setText(_translate("MainLibrator", "User Name"))
        self.label_12.setText(_translate("MainLibrator", "Password"))
        self.label_7.setText(_translate("MainLibrator", "Server IP"))
        self.label_13.setText(_translate("MainLibrator", "Port"))
        self.FragmentTab.setTabText(self.FragmentTab.indexOf(self.tab_5), _translate("MainLibrator", "Remote DB (MySQL)"))
        self.connectFragmentDB.setText(_translate("MainLibrator", "Connect"))
        self.groupBox_6.setTitle(_translate("MainLibrator", "DB content"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFragment), _translate("MainLibrator", "FragmentDB"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tabFragment), _translate("MainLibrator", "Fragment Sequence Database page"))
        self.menuFile.setTitle(_translate("MainLibrator", "File"))
        self.menuSequences.setTitle(_translate("MainLibrator", "Sequences"))
        self.menuTools.setTitle(_translate("MainLibrator", "Tools"))
        self.menuHelp.setTitle(_translate("MainLibrator", "Help"))
        self.menuView.setTitle(_translate("MainLibrator", "View"))
        self.menuSetting.setTitle(_translate("MainLibrator", "Setting"))
        self.menuEdit_Sequence.setTitle(_translate("MainLibrator", "Edit Sequence"))
        self.menuVisualization.setTitle(_translate("MainLibrator", "Visualization"))
        self.menuGibsonClone.setTitle(_translate("MainLibrator", "GibsonClone"))
        self.toolBar.setWindowTitle(_translate("MainLibrator", "toolBar"))
        self.action_Open.setText(_translate("MainLibrator", "&Open"))
        self.action_Open.setToolTip(_translate("MainLibrator", "Open existing Librator database"))
        self.action_Open.setShortcut(_translate("MainLibrator", "Ctrl+O"))
        self.action_New.setText(_translate("MainLibrator", "&New"))
        self.action_New.setToolTip(_translate("MainLibrator", "Create new Librator database"))
        self.action_New.setShortcut(_translate("MainLibrator", "Ctrl+N"))
        self.action_Import.setText(_translate("MainLibrator", "&Import"))
        self.action_Import.setToolTip(_translate("MainLibrator", "Import sequences"))
        self.action_Import.setShortcut(_translate("MainLibrator", "Ctrl+I"))
        self.actionExport.setText(_translate("MainLibrator", "Export"))
        self.actionIMGT.setText(_translate("MainLibrator", "IMGT"))
        self.actionIgBlast.setText(_translate("MainLibrator", "IgBlast"))
        self.actionHANumbering.setText(_translate("MainLibrator", "HA Numbering"))
        self.actionHANumbering.setToolTip(_translate("MainLibrator", "Determine HA Numbering"))
        self.actionMultiple_Alignement.setText(_translate("MainLibrator", "Multiple Alignement (RTF)"))
        self.actionMultiple_Alignement.setIconText(_translate("MainLibrator", "Multiple Sequence Alignement Viewer (RTF)"))
        self.actionMultiple_Alignement.setToolTip(_translate("MainLibrator", "Multiple Sequence Alignement Viewer (RTF)"))
        self.actionImportLei.setText(_translate("MainLibrator", "ImportLei"))
        self.actionImportLei.setToolTip(_translate("MainLibrator", "Import Lei CSV"))
        self.actionImportLei.setShortcut(_translate("MainLibrator", "Ctrl+L"))
        self.actionPreferences.setText(_translate("MainLibrator", "Preferences"))
        self.actionPreferences.setToolTip(_translate("MainLibrator", "Parameter Settings"))
        self.actionPrint.setText(_translate("MainLibrator", "Print"))
        self.actionPrint.setShortcut(_translate("MainLibrator", "Ctrl+P"))
        self.actionPaste_from_Clipboard.setText(_translate("MainLibrator", "Paste from Clipboard"))
        self.actionCopy.setText(_translate("MainLibrator", "Copy"))
        self.actionCopy.setShortcut(_translate("MainLibrator", "Ctrl+C"))
        self.actionCut.setText(_translate("MainLibrator", "Cut"))
        self.actionCut.setShortcut(_translate("MainLibrator", "Ctrl+X"))
        self.actionPaste.setText(_translate("MainLibrator", "Paste"))
        self.actionPaste.setShortcut(_translate("MainLibrator", "Ctrl+V"))
        self.action_Save.setText(_translate("MainLibrator", "&Save"))
        self.action_Save.setShortcut(_translate("MainLibrator", "Ctrl+S"))
        self.actionAbout_2.setText(_translate("MainLibrator", "About"))
        self.action_Help.setText(_translate("MainLibrator", "&Help"))
        self.action_Help.setIconText(_translate("MainLibrator", "Help"))
        self.actionTop.setText(_translate("MainLibrator", "Move &Up"))
        self.actionTop.setToolTip(_translate("MainLibrator", "First record"))
        self.actionTop.setShortcut(_translate("MainLibrator", "Meta+Left"))
        self.actionBottom.setText(_translate("MainLibrator", "Move &Down"))
        self.actionBottom.setToolTip(_translate("MainLibrator", "Last record"))
        self.actionBottom.setShortcut(_translate("MainLibrator", "Meta+Right"))
        self.actionMove_Up.setText(_translate("MainLibrator", "Top"))
        self.actionMove_Up.setToolTip(_translate("MainLibrator", "Previous record"))
        self.actionMove_Up.setShortcut(_translate("MainLibrator", "Meta+Up"))
        self.actionMove_Down.setText(_translate("MainLibrator", "Bottom"))
        self.actionMove_Down.setToolTip(_translate("MainLibrator", "Next record"))
        self.actionMove_Down.setShortcut(_translate("MainLibrator", "Meta+Down"))
        self.actionFind_Clonal.setText(_translate("MainLibrator", "Find Clonal"))
        self.actionSave_As.setText(_translate("MainLibrator", "Save &As"))
        self.actionDelete_record.setText(_translate("MainLibrator", "Delete record"))
        self.actionDelete_record.setToolTip(_translate("MainLibrator", "Delete checked records"))
        self.actionDelete_record.setShortcut(_translate("MainLibrator", "Backspace"))
        self.actionAdd_record.setText(_translate("MainLibrator", "Add record"))
        self.actionDuplicate_current.setText(_translate("MainLibrator", "Duplicate current"))
        self.actionView_subset.setText(_translate("MainLibrator", "View subset"))
        self.actionReport.setText(_translate("MainLibrator", "Report"))
        self.actionGenerate_from_file.setText(_translate("MainLibrator", "Generate from files"))
        self.actionIncrease_font_size.setText(_translate("MainLibrator", "Increase font size"))
        self.actionIncrease_font_size.setShortcut(_translate("MainLibrator", "Meta+="))
        self.actionDecrease_font_size.setText(_translate("MainLibrator", "Decrease font size"))
        self.actionDecrease_font_size.setShortcut(_translate("MainLibrator", "Meta+-"))
        self.actionAlignment_4.setText(_translate("MainLibrator", "Alignment:"))
        self.actionCreateVDJdb.setText(_translate("MainLibrator", "CreateVDJdb"))
        self.actionCreateVDJdb.setToolTip(_translate("MainLibrator", "Creats a new database of VDJ genes from FASTA"))
        self.actionDNA.setText(_translate("MainLibrator", "DNA"))
        self.actionDNA.setToolTip(_translate("MainLibrator", "Include DNA sequence in multiple alignment (RTF)"))
        self.actionAA.setText(_translate("MainLibrator", "AA"))
        self.actionAA.setToolTip(_translate("MainLibrator", "Show amino acids on multiple alignment  (RTF)"))
        self.actionBA.setText(_translate("MainLibrator", "BA"))
        self.actionBA.setToolTip(_translate("MainLibrator", "Align with H1/H3 numbering  (RTF)"))
        self.actionIsotypes.setText(_translate("MainLibrator", "Isotypes"))
        self.actionIsotypes.setToolTip(_translate("MainLibrator", "Show isotype alignment (choose multialignment options for DNA or peptide)"))
        self.actionMap_hotspots.setText(_translate("MainLibrator", "Map hotspots"))
        self.actionMap_hotspots.setToolTip(_translate("MainLibrator", "Generates a report indicating hotspots, coldspots, and C placement to support somatic mutation"))
        self.actionImport_Vgenes_database.setText(_translate("MainLibrator", "Import Vgenes database"))
        self.actionImport_Vgenes_database.setToolTip(_translate("MainLibrator", "imports the contents of a second VGenes database into the current database"))
        self.actionCreateAnalysisDB.setText(_translate("MainLibrator", "Create analysis DB"))
        self.actionCreateAnalysisDB.setToolTip(_translate("MainLibrator", "Creates a database from IMGT formatted FASTA files"))
        self.actionTree.setText(_translate("MainLibrator", "Generate Maximum Likelihood Tree (Amino Acid)"))
        self.actionTree.setToolTip(_translate("MainLibrator", "Generate Maximum Likelihood Tree (Using Amino Acid sequences)"))
        self.actionRevert_to_previous.setText(_translate("MainLibrator", "Revert to previous"))
        self.actionRevert_to_previous.setToolTip(_translate("MainLibrator", "Revert current file to the state when this instance of VGenes was opened"))
        self.actionAnalyze_Isotypes.setText(_translate("MainLibrator", "Analyze Isotypes"))
        self.actionAnalyze_Isotypes.setToolTip(_translate("MainLibrator", "Analyzes the isotypes of checked records"))
        self.actionMerge_fastq_Ends.setText(_translate("MainLibrator", "Merge fastq Ends"))
        self.actionMergeMySeq.setText(_translate("MainLibrator", "MergeMySeq"))
        self.actionMergeMySeq.setToolTip(_translate("MainLibrator", "Merge two matched end fatq files"))
        self.actionImportCluster.setText(_translate("MainLibrator", "Import Cluster"))
        self.actionRename10x.setText(_translate("MainLibrator", "Rename 10X Barcodes"))
        self.actionFixNames.setText(_translate("MainLibrator", "FixNames"))
        self.actionOpen_last.setText(_translate("MainLibrator", "Open Last"))
        self.actionClean.setText(_translate("MainLibrator", "Clean TEMP files"))
        self.actionNTTree.setText(_translate("MainLibrator", "Generate Maximum Likelihood Tree (nucleotide)"))
        self.actionNTTree.setToolTip(_translate("MainLibrator", "Generate Maximum Likelihood Tree (Using nucleotide sequences)"))
        self.actionCheck_Update_base_folder.setText(_translate("MainLibrator", "Set PATH"))
        self.actionMutation.setText(_translate("MainLibrator", "Mutation"))
        self.actionMutation.setToolTip(_translate("MainLibrator", "Generate Sequences with specific mutations"))
        self.actionEditing.setText(_translate("MainLibrator", "Editing"))
        self.actionEditing.setToolTip(_translate("MainLibrator", "Edit sequences with Base biased mode or Cocktail mode"))
        self.actionFusion.setText(_translate("MainLibrator", "Fusion"))
        self.actionFusion.setToolTip(_translate("MainLibrator", "Fuse two sequences of different subtypes"))
        self.actionPyMOL.setText(_translate("MainLibrator", "PyMOL"))
        self.actionPyMOL.setToolTip(_translate("MainLibrator", "Use PyMOL to visualize 3D structure"))
        self.actionGibsonClone.setText(_translate("MainLibrator", "GibsonClone"))
        self.actionGibsonClone.setToolTip(_translate("MainLibrator", "Generate Fragments for Gibson Clone use"))
        self.actionGibsonClone_Setting.setText(_translate("MainLibrator", "GibsonClone Setting"))
        self.actionAlignmentHTML.setText(_translate("MainLibrator", "Multiple Alignment (HTML)"))
        self.actionAlignmentHTML.setIconText(_translate("MainLibrator", "Multiple Sequence Alignment Viewer (HTML)"))
        self.actionAlignmentHTML.setToolTip(_translate("MainLibrator", "Multiple Sequence Alignment Viewer (HTML)"))
        self.actionVector_Joint_Setting.setText(_translate("MainLibrator", "Vector Joint Setting"))
        self.actionFusion_High_resolution.setText(_translate("MainLibrator", "Fusion (High resolution)"))
        self.actionFusion_Low_reslution.setText(_translate("MainLibrator", "Fusion (Low reslution)"))
import VgenesResources_rc
