# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sequenceedit.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SequenceEditDialog(object):
    def setupUi(self, SequenceEditDialog):
        SequenceEditDialog.setObjectName("SequenceEditDialog")
        SequenceEditDialog.resize(1098, 1026)
        self.gridLayout = QtWidgets.QGridLayout(SequenceEditDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.BaseSeqLabel = QtWidgets.QLabel(SequenceEditDialog)
        self.BaseSeqLabel.setMaximumSize(QtCore.QSize(200, 16777215))
        self.BaseSeqLabel.setObjectName("BaseSeqLabel")
        self.gridLayout.addWidget(self.BaseSeqLabel, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.GenerateSeq = QtWidgets.QPushButton(SequenceEditDialog)
        self.GenerateSeq.setDefault(True)
        self.GenerateSeq.setObjectName("GenerateSeq")
        self.horizontalLayout.addWidget(self.GenerateSeq)
        self.Cancel = QtWidgets.QPushButton(SequenceEditDialog)
        self.Cancel.setAutoDefault(True)
        self.Cancel.setObjectName("Cancel")
        self.horizontalLayout.addWidget(self.Cancel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 2)
        self.BaseSeqName = QtWidgets.QLabel(SequenceEditDialog)
        self.BaseSeqName.setObjectName("BaseSeqName")
        self.gridLayout.addWidget(self.BaseSeqName, 0, 1, 1, 1)
        self.ModeTab = QtWidgets.QTabWidget(SequenceEditDialog)
        self.ModeTab.setObjectName("ModeTab")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 300))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.DonorList_tab2 = QtWidgets.QListWidget(self.groupBox_2)
        self.DonorList_tab2.setMaximumSize(QtCore.QSize(16777215, 300))
        self.DonorList_tab2.setObjectName("DonorList_tab2")
        self.gridLayout_3.addWidget(self.DonorList_tab2, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_2, 0, 0, 1, 2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 2, 1, 1)
        self.ApplyDonorRegion = QtWidgets.QPushButton(self.groupBox_4)
        self.ApplyDonorRegion.setObjectName("ApplyDonorRegion")
        self.gridLayout_4.addWidget(self.ApplyDonorRegion, 0, 5, 1, 1)
        self.spinBoxTo = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBoxTo.setMinimumSize(QtCore.QSize(60, 0))
        self.spinBoxTo.setMaximum(5000)
        self.spinBoxTo.setProperty("value", 5000)
        self.spinBoxTo.setObjectName("spinBoxTo")
        self.gridLayout_4.addWidget(self.spinBoxTo, 0, 3, 1, 1)
        self.spinBoxFrom = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBoxFrom.setMinimumSize(QtCore.QSize(60, 0))
        self.spinBoxFrom.setMaximum(5000)
        self.spinBoxFrom.setObjectName("spinBoxFrom")
        self.gridLayout_4.addWidget(self.spinBoxFrom, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_4)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 0, 4, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_4, 1, 0, 1, 2)
        self.groupBoxSeqComp = QtWidgets.QGroupBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.groupBoxSeqComp.setFont(font)
        self.groupBoxSeqComp.setObjectName("groupBoxSeqComp")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBoxSeqComp)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_7.addWidget(self.groupBoxSeqComp, 2, 0, 1, 2)
        self.radioButton_single = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_single.setMaximumSize(QtCore.QSize(16777215, 20))
        self.radioButton_single.setChecked(True)
        self.radioButton_single.setObjectName("radioButton_single")
        self.gridLayout_7.addWidget(self.radioButton_single, 3, 0, 1, 1)
        self.radioButton_all = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_all.setMaximumSize(QtCore.QSize(16777215, 20))
        self.radioButton_all.setChecked(False)
        self.radioButton_all.setObjectName("radioButton_all")
        self.gridLayout_7.addWidget(self.radioButton_all, 3, 1, 1, 1)
        self.ModeTab.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.DonorList_tab1 = QtWidgets.QListWidget(self.groupBox_3)
        self.DonorList_tab1.setObjectName("DonorList_tab1")
        self.gridLayout_2.addWidget(self.DonorList_tab1, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.ModeTab.addTab(self.tab, "")
        self.gridLayout.addWidget(self.ModeTab, 1, 0, 1, 2)

        self.retranslateUi(SequenceEditDialog)
        self.ModeTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SequenceEditDialog)

    def retranslateUi(self, SequenceEditDialog):
        _translate = QtCore.QCoreApplication.translate
        SequenceEditDialog.setWindowTitle(_translate("SequenceEditDialog", "Edit Sequences"))
        self.BaseSeqLabel.setText(_translate("SequenceEditDialog", "Base Sequence"))
        self.GenerateSeq.setText(_translate("SequenceEditDialog", "Genearate Sequences"))
        self.Cancel.setText(_translate("SequenceEditDialog", "Cancel"))
        self.BaseSeqName.setText(_translate("SequenceEditDialog", "Base Sequence"))
        self.groupBox_2.setTitle(_translate("SequenceEditDialog", "Donor sequence (single selection)"))
        self.groupBox_4.setTitle(_translate("SequenceEditDialog", "Donor Region"))
        self.label_2.setText(_translate("SequenceEditDialog", "To: "))
        self.ApplyDonorRegion.setText(_translate("SequenceEditDialog", "Apply"))
        self.label.setText(_translate("SequenceEditDialog", "From: "))
        self.groupBoxSeqComp.setTitle(_translate("SequenceEditDialog", "Sequence Comparision"))
        self.radioButton_single.setText(_translate("SequenceEditDialog", "Only single muitations"))
        self.radioButton_all.setText(_translate("SequenceEditDialog", "All possible combinations"))
        self.ModeTab.setTabText(self.ModeTab.indexOf(self.tab_2), _translate("SequenceEditDialog", "Cocktail"))
        self.groupBox_3.setTitle(_translate("SequenceEditDialog", "Donor Sequences (multiple selection)"))
        self.ModeTab.setTabText(self.ModeTab.indexOf(self.tab), _translate("SequenceEditDialog", "Base Biased"))
