# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'treedialog.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_treeDialog(object):
    def setupUi(self, treeDialog):
        treeDialog.setObjectName("treeDialog")
        treeDialog.resize(1163, 804)
        self.label = QtWidgets.QLabel(treeDialog)
        self.label.setGeometry(QtCore.QRect(30, 20, 391, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.seqEdit = QtWidgets.QTextEdit(treeDialog)
        self.seqEdit.setGeometry(QtCore.QRect(300, 50, 841, 671))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(15)
        self.seqEdit.setFont(font)
        self.seqEdit.setLineWidth(1)
        self.seqEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.seqEdit.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.seqEdit.setLineWrapColumnOrWidth(0)
        self.seqEdit.setObjectName("seqEdit")
        self.horizontalLayoutWidget = QtWidgets.QWidget(treeDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(780, 760, 361, 32))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.confirmButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.confirmButton.setCheckable(True)
        self.confirmButton.setChecked(True)
        self.confirmButton.setObjectName("confirmButton")
        self.horizontalLayout.addWidget(self.confirmButton)
        self.cancelButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.label_3 = QtWidgets.QLabel(treeDialog)
        self.label_3.setGeometry(QtCore.QRect(30, 730, 511, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(treeDialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(30, 760, 371, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.startBox = QtWidgets.QSpinBox(self.horizontalLayoutWidget_2)
        self.startBox.setMaximum(5000)
        self.startBox.setObjectName("startBox")
        self.horizontalLayout_2.addWidget(self.startBox)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.endBox = QtWidgets.QSpinBox(self.horizontalLayoutWidget_2)
        self.endBox.setMaximum(5000)
        self.endBox.setObjectName("endBox")
        self.horizontalLayout_2.addWidget(self.endBox)
        self.nameList = QtWidgets.QListWidget(treeDialog)
        self.nameList.setGeometry(QtCore.QRect(30, 51, 261, 671))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        self.nameList.setFont(font)
        self.nameList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.nameList.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.nameList.setObjectName("nameList")
        self.showButton = QtWidgets.QPushButton(treeDialog)
        self.showButton.setGeometry(QtCore.QRect(410, 760, 181, 32))
        self.showButton.setObjectName("showButton")
        self.lbl = QtWidgets.QLabel(treeDialog)
        self.lbl.setGeometry(QtCore.QRect(420, 20, 721, 20))
        self.lbl.setObjectName("lbl")

        self.retranslateUi(treeDialog)
        QtCore.QMetaObject.connectSlotsByName(treeDialog)

    def retranslateUi(self, treeDialog):
        _translate = QtCore.QCoreApplication.translate
        treeDialog.setWindowTitle(_translate("treeDialog", "Alignment Reviewer"))
        self.label.setText(_translate("treeDialog", "Review alignment of your selected sequences:"))
        self.confirmButton.setText(_translate("treeDialog", "Generate Tree"))
        self.cancelButton.setText(_translate("treeDialog", "Cancel"))
        self.label_3.setText(_translate("treeDialog", "Determine region:"))
        self.label_2.setText(_translate("treeDialog", "Start:(0-5000)"))
        self.label_4.setText(_translate("treeDialog", "End:(0-5000)"))
        self.showButton.setText(_translate("treeDialog", "Highlight selected region"))
        self.lbl.setText(_translate("treeDialog", "Sequence: "))


