# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'treedialog.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_treeDialog(object):
    def setupUi(self, treeDialog):
        treeDialog.setObjectName("treeDialog")
        treeDialog.resize(1268, 611)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(treeDialog.sizePolicy().hasHeightForWidth())
        treeDialog.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(treeDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(treeDialog)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)
        self.lbl = QtWidgets.QLabel(treeDialog)
        self.lbl.setObjectName("lbl")
        self.gridLayout.addWidget(self.lbl, 0, 3, 1, 2)
        self.nameList = QtWidgets.QListWidget(treeDialog)
        self.nameList.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        self.nameList.setFont(font)
        self.nameList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.nameList.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.nameList.setObjectName("nameList")
        self.gridLayout.addWidget(self.nameList, 1, 0, 1, 1)
        self.seqEdit = QtWidgets.QTextEdit(treeDialog)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(15)
        self.seqEdit.setFont(font)
        self.seqEdit.setLineWidth(1)
        self.seqEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.seqEdit.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.seqEdit.setLineWrapColumnOrWidth(0)
        self.seqEdit.setObjectName("seqEdit")
        self.gridLayout.addWidget(self.seqEdit, 1, 1, 1, 4)
        self.label_3 = QtWidgets.QLabel(treeDialog)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(treeDialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.startBox = QtWidgets.QSpinBox(treeDialog)
        self.startBox.setMaximum(5000)
        self.startBox.setObjectName("startBox")
        self.horizontalLayout_2.addWidget(self.startBox)
        self.label_4 = QtWidgets.QLabel(treeDialog)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.endBox = QtWidgets.QSpinBox(treeDialog)
        self.endBox.setMaximum(5000)
        self.endBox.setObjectName("endBox")
        self.horizontalLayout_2.addWidget(self.endBox)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 2)
        self.showButton = QtWidgets.QPushButton(treeDialog)
        self.showButton.setObjectName("showButton")
        self.gridLayout.addWidget(self.showButton, 3, 2, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.confirmButton = QtWidgets.QPushButton(treeDialog)
        self.confirmButton.setCheckable(True)
        self.confirmButton.setChecked(True)
        self.confirmButton.setObjectName("confirmButton")
        self.horizontalLayout.addWidget(self.confirmButton)
        self.cancelButton = QtWidgets.QPushButton(treeDialog)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 4, 1, 1)

        self.retranslateUi(treeDialog)
        QtCore.QMetaObject.connectSlotsByName(treeDialog)

    def retranslateUi(self, treeDialog):
        _translate = QtCore.QCoreApplication.translate
        treeDialog.setWindowTitle(_translate("treeDialog", "Alignment Reviewer"))
        self.label.setText(_translate("treeDialog", "Review alignment of your selected sequences:"))
        self.lbl.setText(_translate("treeDialog", "Sequence: "))
        self.label_3.setText(_translate("treeDialog", "Determine region:"))
        self.label_2.setText(_translate("treeDialog", "Start:(0-5000)"))
        self.label_4.setText(_translate("treeDialog", "End:(0-5000)"))
        self.showButton.setText(_translate("treeDialog", "Highlight selected region"))
        self.confirmButton.setText(_translate("treeDialog", "Generate Tree"))
        self.cancelButton.setText(_translate("treeDialog", "Cancel"))


