# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainLibrator_UI.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainLibrator(object):
    def setupUi(self, MainLibrator):
        MainLibrator.setObjectName("MainLibrator")
        MainLibrator.resize(1029, 989)
        self.centralwidget = QtWidgets.QWidget(MainLibrator)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 1021, 1031))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1019, 1029))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 1001, 971))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textBaseSeqName = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.textBaseSeqName.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textBaseSeqName.setObjectName("textBaseSeqName")
        self.gridLayout_2.addWidget(self.textBaseSeqName, 4, 0, 1, 1)
        self.textBaseAA = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.textBaseAA.setMaximumSize(QtCore.QSize(16777215, 100))
        self.textBaseAA.setObjectName("textBaseAA")
        self.gridLayout_2.addWidget(self.textBaseAA, 8, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 5, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 7, 0, 1, 1)
        self.textBaseSeq = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.textBaseSeq.setMaximumSize(QtCore.QSize(16777215, 100))
        self.textBaseSeq.setObjectName("textBaseSeq")
        self.gridLayout_2.addWidget(self.textBaseSeq, 6, 0, 1, 1)
        self.btnImportBase = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnImportBase.setObjectName("btnImportBase")
        self.gridLayout_2.addWidget(self.btnImportBase, 9, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 3, 0, 1, 1)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.btnClearStrain_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnClearStrain_2.setObjectName("btnClearStrain_2")
        self.gridLayout_13.addWidget(self.btnClearStrain_2, 5, 3, 1, 1)
        self.btnClearStrain = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnClearStrain.setObjectName("btnClearStrain")
        self.gridLayout_13.addWidget(self.btnClearStrain, 5, 5, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_63.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_63.setObjectName("label_63")
        self.gridLayout_13.addWidget(self.label_63, 4, 0, 1, 1)
        self.spnWindow_Base = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spnWindow_Base.setMaximumSize(QtCore.QSize(75, 16777215))
        self.spnWindow_Base.setObjectName("spnWindow_Base")
        self.gridLayout_13.addWidget(self.spnWindow_Base, 5, 1, 1, 1)
        self.label_67 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_67.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_67.setObjectName("label_67")
        self.gridLayout_13.addWidget(self.label_67, 5, 0, 1, 1)
        self.listWidgetStrains = QtWidgets.QListWidget(self.gridLayoutWidget)
        self.listWidgetStrains.setMaximumSize(QtCore.QSize(16777215, 60))
        self.listWidgetStrains.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.listWidgetStrains.setAlternatingRowColors(True)
        self.listWidgetStrains.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidgetStrains.setObjectName("listWidgetStrains")
        self.gridLayout_13.addWidget(self.listWidgetStrains, 4, 3, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_29.setObjectName("label_29")
        self.gridLayout_13.addWidget(self.label_29, 3, 5, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_28.setObjectName("label_28")
        self.gridLayout_13.addWidget(self.label_28, 3, 3, 1, 1)
        self.cmbListBase = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cmbListBase.setMinimumSize(QtCore.QSize(300, 0))
        self.cmbListBase.setObjectName("cmbListBase")
        self.cmbListBase.addItem("")
        self.gridLayout_13.addWidget(self.cmbListBase, 0, 5, 1, 1)
        self.listWidgetStrainsIn = QtWidgets.QListWidget(self.gridLayoutWidget)
        self.listWidgetStrainsIn.setMaximumSize(QtCore.QSize(16777215, 60))
        self.listWidgetStrainsIn.setDragDropOverwriteMode(True)
        self.listWidgetStrainsIn.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        self.listWidgetStrainsIn.setAlternatingRowColors(True)
        self.listWidgetStrainsIn.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidgetStrainsIn.setObjectName("listWidgetStrainsIn")
        self.gridLayout_13.addWidget(self.listWidgetStrainsIn, 4, 5, 1, 1)
        self.txtInsert_Base = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.txtInsert_Base.setMinimumSize(QtCore.QSize(0, 0))
        self.txtInsert_Base.setMaximumSize(QtCore.QSize(16777215, 60))
        self.txtInsert_Base.setObjectName("txtInsert_Base")
        self.gridLayout_13.addWidget(self.txtInsert_Base, 4, 1, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_65.setMinimumSize(QtCore.QSize(300, 0))
        self.label_65.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_65.setObjectName("label_65")
        self.gridLayout_13.addWidget(self.label_65, 0, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_13, 11, 0, 1, 1)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_48 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_48.setObjectName("label_48")
        self.gridLayout_11.addWidget(self.label_48, 0, 0, 1, 1)
        self.spnFragments = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spnFragments.setMinimum(1)
        self.spnFragments.setProperty("value", 5)
        self.spnFragments.setObjectName("spnFragments")
        self.gridLayout_11.addWidget(self.spnFragments, 1, 1, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 100))
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_11.addWidget(self.textEdit, 2, 1, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_61.setObjectName("label_61")
        self.gridLayout_11.addWidget(self.label_61, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_11.addWidget(self.pushButton, 3, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_11, 10, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_66 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_66.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_66.setObjectName("label_66")
        self.gridLayout_3.addWidget(self.label_66, 0, 3, 1, 1)
        self.cmbForm_Base = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cmbForm_Base.setObjectName("cmbForm_Base")
        self.cmbForm_Base.addItem("")
        self.cmbForm_Base.addItem("")
        self.cmbForm_Base.addItem("")
        self.cmbForm_Base.addItem("")
        self.cmbForm_Base.addItem("")
        self.gridLayout_3.addWidget(self.cmbForm_Base, 1, 2, 1, 1)
        self.label_64 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_64.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_64.setObjectName("label_64")
        self.gridLayout_3.addWidget(self.label_64, 0, 2, 1, 1)
        self.cboActive = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cboActive.setObjectName("cboActive")
        self.gridLayout_3.addWidget(self.cboActive, 1, 1, 1, 1)
        self.cmbSubtypes_Base = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cmbSubtypes_Base.setObjectName("cmbSubtypes_Base")
        self.cmbSubtypes_Base.addItem("")
        self.cmbSubtypes_Base.addItem("")
        self.cmbSubtypes_Base.addItem("")
        self.cmbSubtypes_Base.addItem("")
        self.cmbSubtypes_Base.addItem("")
        self.cmbSubtypes_Base.addItem("")
        self.gridLayout_3.addWidget(self.cmbSubtypes_Base, 1, 3, 1, 1)
        self.label_68 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_68.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_68.setObjectName("label_68")
        self.gridLayout_3.addWidget(self.label_68, 0, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 281, 150))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.radioButton_3 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout.addWidget(self.radioButton_3)
        self.radioButton_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.radioButton_2)
        self.radioButton_5 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_5.setObjectName("radioButton_5")
        self.verticalLayout.addWidget(self.radioButton_5)
        self.radioButton_4 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout.addWidget(self.radioButton_4)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.gridLayout_3.addWidget(self.frame, 2, 1, 2, 1)
        self.txtDonorRegions = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.txtDonorRegions.setMaximumSize(QtCore.QSize(300, 75))
        self.txtDonorRegions.setObjectName("txtDonorRegions")
        self.gridLayout_3.addWidget(self.txtDonorRegions, 2, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 2, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainLibrator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainLibrator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1029, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainLibrator.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainLibrator)
        self.statusbar.setObjectName("statusbar")
        MainLibrator.setStatusBar(self.statusbar)
        self.action_New = QtWidgets.QAction(MainLibrator)
        self.action_New.setObjectName("action_New")
        self.action_Open = QtWidgets.QAction(MainLibrator)
        self.action_Open.setObjectName("action_Open")
        self.action_Close = QtWidgets.QAction(MainLibrator)
        self.action_Close.setObjectName("action_Close")
        self.action_Close_2 = QtWidgets.QAction(MainLibrator)
        self.action_Close_2.setObjectName("action_Close_2")
        self.menuFile.addAction(self.action_New)
        self.menuFile.addAction(self.action_Open)
        self.menuFile.addAction(self.action_Close)
        self.menuFile.addAction(self.action_Close_2)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainLibrator)
        QtCore.QMetaObject.connectSlotsByName(MainLibrator)

    def retranslateUi(self, MainLibrator):
        _translate = QtCore.QCoreApplication.translate
        MainLibrator.setWindowTitle(_translate("MainLibrator", "MainWindow"))
        self.label_2.setText(_translate("MainLibrator", "Base Coding Sequence:"))
        self.label_3.setText(_translate("MainLibrator", "Base Amino Acid Sequence:"))
        self.btnImportBase.setText(_translate("MainLibrator", "Import Base Sequence"))
        self.label.setText(_translate("MainLibrator", "Base Sequence name:"))
        self.btnClearStrain_2.setText(_translate("MainLibrator", "Import Sequences"))
        self.btnClearStrain.setText(_translate("MainLibrator", "Clear List"))
        self.label_63.setText(_translate("MainLibrator", "Mutations:"))
        self.label_67.setText(_translate("MainLibrator", "Window:"))
        self.listWidgetStrains.setSortingEnabled(True)
        self.label_29.setText(_translate("MainLibrator", "Active sequences:"))
        self.label_28.setText(_translate("MainLibrator", "Available sequences:"))
        self.cmbListBase.setItemText(0, _translate("MainLibrator", "New"))
        self.listWidgetStrainsIn.setSortingEnabled(True)
        self.label_65.setText(_translate("MainLibrator", "Sequence choices:"))
        self.label_48.setText(_translate("MainLibrator", "Results:"))
        self.label_61.setText(_translate("MainLibrator", "Gibson Fragments:"))
        self.pushButton.setText(_translate("MainLibrator", "Generate Report"))
        self.label_66.setText(_translate("MainLibrator", "Subtype:"))
        self.cmbForm_Base.setItemText(0, _translate("MainLibrator", "Full HA"))
        self.cmbForm_Base.setItemText(1, _translate("MainLibrator", "Probe HA"))
        self.cmbForm_Base.setItemText(2, _translate("MainLibrator", "Full NA"))
        self.cmbForm_Base.setItemText(3, _translate("MainLibrator", "Probe NA"))
        self.cmbForm_Base.setItemText(4, _translate("MainLibrator", "Other"))
        self.label_64.setText(_translate("MainLibrator", "Form:"))
        self.cmbSubtypes_Base.setItemText(0, _translate("MainLibrator", "H1N1"))
        self.cmbSubtypes_Base.setItemText(1, _translate("MainLibrator", "H3N2"))
        self.cmbSubtypes_Base.setItemText(2, _translate("MainLibrator", "B"))
        self.cmbSubtypes_Base.setItemText(3, _translate("MainLibrator", "Group 1"))
        self.cmbSubtypes_Base.setItemText(4, _translate("MainLibrator", "Group 2"))
        self.cmbSubtypes_Base.setItemText(5, _translate("MainLibrator", "Other"))
        self.label_68.setText(_translate("MainLibrator", "Active HA:"))
        self.label_4.setText(_translate("MainLibrator", "Mosaic options:"))
        self.radioButton_3.setText(_translate("MainLibrator", "Base"))
        self.radioButton_2.setText(_translate("MainLibrator", "Base Biased"))
        self.radioButton_5.setText(_translate("MainLibrator", "Cocktail"))
        self.radioButton_4.setText(_translate("MainLibrator", "Biased cocktail"))
        self.label_5.setText(_translate("MainLibrator", "Donor regions:"))
        self.menuFile.setTitle(_translate("MainLibrator", "File"))
        self.action_New.setText(_translate("MainLibrator", "&New"))
        self.action_Open.setText(_translate("MainLibrator", "&Open"))
        self.action_Close.setText(_translate("MainLibrator", "&Save"))
        self.action_Close_2.setText(_translate("MainLibrator", "&Close"))


